// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Code generated by tygo from internal/httpapi. DO NOT EDIT.
//
// Regenerate with `make web-types`. CI fails if this file is out of date
// with the Go structs it came from.

//////////
// source: coverage.go

/**
 * CoverageResponse describes what is actually in the database.
 * It exists because the project has a real gap — full-schema data runs out in
 * January 2026 for the ATP and December 2024 for the WTA — and ADR-0006 chose to
 * accept it and say so. Saying so from a hardcoded date would drift the first
 * time an ingest moved it, so every number here is queried.
 */
export interface CoverageResponse {
  /**
   * CurrentThrough is the most recent match per tour, which is the honest
   * answer to "how up to date is this site".
   */
  current_through: { [key: string]: string};
  tiers: CoverageEntry[];
}
/**
 * CoverageEntry is one tour and tier.
 */
export interface CoverageEntry {
  tour: string;
  tier: string;
  matches: number /* int64 */;
  first_match: string;
  last_match: string;
  matches_with_stats: number /* int64 */;
  stats_percentage: number /* float64 */;
}

//////////
// source: cursor.go

/**
 * Page is the envelope for every list response. NextCursor is empty on the last
 * page, which is how a client knows to stop.
 */
export interface Page<T extends any> {
  data: T[];
  next_cursor: string | null;
}

//////////
// source: matches.go

/**
 * PlayerMatch is one match in a player's history, from that player's side.
 */
export interface PlayerMatch {
  date: string;
  tournament: string;
  tier: string;
  level: string;
  season: number /* int16 */;
  round: string;
  qualifying: boolean;
  surface: string | null;
  opponent: Opponent;
  won: boolean;
  score: string | null;
  incomplete: boolean;
  minutes: number /* int16 */ | null;
  serve: MatchServe;
}
/**
 * Opponent is the other player, named well enough to link to.
 */
export interface Opponent {
  slug: string;
  name: string;
}
/**
 * MatchServe is this player's serve line for one match. Every count is a
 * pointer: the source recorded nothing for 83% of the matches in the database,
 * and a zero would read as a player who served and achieved nothing.
 */
export interface MatchServe {
  /**
   * Availability is why the counts are absent when they are, using the same
   * vocabulary as the profile endpoint.
   */
  availability: string;
  aces: number /* int16 */ | null;
  double_faults: number /* int16 */ | null;
  serve_points: number /* int16 */ | null;
  first_in: number /* int16 */ | null;
  first_won: number /* int16 */ | null;
  second_won: number /* int16 */ | null;
  serve_games: number /* int16 */ | null;
  break_points_saved: number /* int16 */ | null;
  break_points_faced: number /* int16 */ | null;
}

//////////
// source: players.go

/**
 * AvailabilityRecorded means every eligible match carried statistics.
 */
export const AvailabilityRecorded = "recorded";
/**
 * AvailabilityPartial means some did and some did not.
 */
export const AvailabilityPartial = "partial";
/**
 * AvailabilityNeverForTier means no match at this player's level has ever
 * recorded serve statistics — Futures and ITF, in any year.
 */
export const AvailabilityNeverForTier = "never_recorded_for_tier";
/**
 * AvailabilityNeverInEra means the matches predate the recording of them:
 * before 1991 anywhere, and before roughly 2010 at Challenger level.
 */
export const AvailabilityNeverInEra = "never_recorded_in_era";
/**
 * AvailabilityNotRecorded is the honest fallback: absent, reason unknown.
 */
export const AvailabilityNotRecorded = "not_recorded";
/**
 * PlayerProfile is the response for a single player.
 */
export interface PlayerProfile {
  slug: string;
  name: string;
  tour: string;
  country: string | null;
  hand: string | null;
  height_cm: number /* int16 */ | null;
  birth_date: string | null;
  pro_since: number /* int16 */ | null;
  /**
   * Career is null for a player with no ingested matches, which is not the
   * same as a career of zeroes.
   */
  career: Career | null;
  serve: ServeStats;
}
/**
 * Career is the win/loss record. Retirements and walkovers are counted here and
 * excluded from every rate in Serve.
 */
export interface Career {
  matches: number /* int64 */;
  wins: number /* int64 */;
  losses: number /* int64 */;
  win_percentage: number /* float64 */;
  titles: number /* int64 */;
  incomplete_matches: number /* int64 */;
  first_match: string;
  last_match: string;
  surfaces: SurfaceSplit[];
  tiers: TierSplit[];
}
/**
 * SurfaceSplit is a win/loss record on one surface.
 */
export interface SurfaceSplit {
  surface: string;
  matches: number /* int64 */;
  wins: number /* int64 */;
  losses: number /* int64 */;
}
/**
 * TierSplit reports how many matches at a tier recorded statistics, which is
 * what makes "never recorded at this level" a checkable claim.
 */
export interface TierSplit {
  tier: string;
  matches: number /* int64 */;
  matches_with_stats: number /* int64 */;
}
/**
 * ServeStats carries the serve statistics, or the reason there are none.
 */
export interface ServeStats {
  availability: string;
  matches_with_data: number /* int64 */;
  rates: ServeRates | null;
}
/**
 * ServeRates are percentages and per-match averages. A nil field is a rate with
 * no denominator, which is different from a rate that is zero: a player who
 * never faced a break point has not saved 0% of them.
 */
export interface ServeRates {
  aces_per_match: number /* float64 */;
  double_faults_per_match: number /* float64 */;
  first_serve_in_percentage: number /* float64 */ | null;
  first_serve_won_percentage: number /* float64 */ | null;
  second_serve_won_percentage: number /* float64 */ | null;
  break_points_saved_percentage: number /* float64 */ | null;
}
/**
 * PlayerSearchResult is one row of the search response.
 */
export interface PlayerSearchResult {
  slug: string;
  name: string;
  tour: string;
  country: string | null;
  matches: number /* int64 */;
  best_tier: string | null;
  score: number /* float32 */;
}

//////////
// source: problem.go

/**
 * ProblemContentType is the media type RFC 7807 defines for error bodies.
 */
export const ProblemContentType = "application/problem+json";
/**
 * Problem is an RFC 7807 problem document. Every error this API returns is one
 * of these, so a client needs exactly one error shape.
 */
export interface Problem {
  /**
   * Type is a URI reference identifying the problem kind. Clients should
   * switch on this rather than on Title, which is for humans.
   */
  type: string;
  title: string;
  status: number /* int */;
  detail: string | null;
  instance: string | null;
  request_id: string | null;
}
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeNotFound = "/problems/not-found";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeBadRequest = "/problems/bad-request";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeRateLimited = "/problems/rate-limited";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeInternal = "/problems/internal";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeUnavailable = "/problems/unavailable";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeMethodInvalid = "/problems/method-not-allowed";
