// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Code generated by tygo from internal/httpapi. DO NOT EDIT.
//
// Regenerate with `make web-types`. CI fails if this file is out of date
// with the Go structs it came from.

/** A Go [2]T. Everything the head-to-head pairs is in the order the URL asked for. */
export type Pair<T> = [T, T]

//////////
// source: coverage.go

/**
 * CoverageResponse describes what is actually in the database.
 * It exists because the project has a real gap — full-schema data runs out in
 * January 2026 for the ATP and December 2024 for the WTA — and ADR-0006 chose to
 * accept it and say so. Saying so from a hardcoded date would drift the first
 * time an ingest moved it, so every number here is queried.
 */
export interface CoverageResponse {
  /**
   * CurrentThrough is the most recent match per tour, which is the honest
   * answer to "how up to date is this site".
   */
  current_through: { [key: string]: string};
  tiers: CoverageEntry[];
}
/**
 * CoverageEntry is one tour and tier.
 */
export interface CoverageEntry {
  tour: string;
  tier: string;
  matches: number /* int64 */;
  first_match: string;
  last_match: string;
  matches_with_stats: number /* int64 */;
  stats_percentage: number /* float64 */;
}

//////////
// source: cursor.go

/**
 * Page is the envelope for every list response. NextCursor is empty on the last
 * page, which is how a client knows to stop.
 */
export interface Page<T extends any> {
  data: T[];
  next_cursor: string | null;
}

//////////
// source: h2h.go

/**
 * HeadToHead is one comparison between two players.
 * Everything paired is a two-element array in the order the URL asked for, so
 * /h2h/a/b and /h2h/b/a are the same comparison read from opposite ends rather
 * than two pages that could disagree.
 */
export interface HeadToHead {
  /**
   * tstype Pair, because a Go array of two marshals to a plain JSON array and
   * the generated type would otherwise promise only "some players" -- losing
   * the one guarantee this shape is built on.
   */
  players: Pair<HeadToHeadPlayer>;
  record: HeadToHeadRecord;
  /**
   * Surfaces and Tiers exist because a 3-1 record that is really 3-1 at
   * Futures is a different claim from 3-1 at tour level.
   */
  surfaces: HeadToHeadSplit[];
  tiers: HeadToHeadSplit[];
  serve: Pair<ServeStats>;
  meetings: Meeting[];
}
/**
 * HeadToHeadPlayer is enough of a player to head a column.
 */
export interface HeadToHeadPlayer {
  slug: string;
  name: string;
  tour: string;
  country: string | null;
}
/**
 * HeadToHeadRecord is the score between them.
 */
export interface HeadToHeadRecord {
  matches: number /* int */;
  wins: Pair<number>;
  /**
   * Incomplete counts retirements and walkovers. They belong in the record --
   * somebody advanced -- and are excluded from every rate.
   */
  incomplete: number /* int */;
}
/**
 * HeadToHeadSplit is the record inside one surface or one tier.
 */
export interface HeadToHeadSplit {
  name: string;
  matches: number /* int */;
  wins: Pair<number>;
}
/**
 * Meeting is one match between the two, from neither side.
 */
export interface Meeting {
  date: string;
  tournament: string;
  tier: string;
  level: string;
  season: number /* int16 */;
  round: string;
  qualifying: boolean;
  surface: string | null;
  /**
   * WinnerIndex is 0 or 1, indexing Players. An index rather than a slug so
   * a caller cannot mix up which end of the comparison it is reading.
   */
  winner_index: number /* int */;
  score: string | null;
  incomplete: boolean;
}

//////////
// source: matches.go

/**
 * PlayerMatch is one match in a player's history, from that player's side.
 */
export interface PlayerMatch {
  date: string;
  tournament: string;
  tier: string;
  level: string;
  season: number /* int16 */;
  round: string;
  qualifying: boolean;
  surface: string | null;
  opponent: Opponent;
  won: boolean;
  score: string | null;
  incomplete: boolean;
  minutes: number /* int16 */ | null;
  serve: MatchServe;
}
/**
 * Opponent is the other player, named well enough to link to.
 */
export interface Opponent {
  slug: string;
  name: string;
}
/**
 * MatchServe is this player's serve line for one match. Every count is a
 * pointer: the source recorded nothing for 83% of the matches in the database,
 * and a zero would read as a player who served and achieved nothing.
 */
export interface MatchServe {
  /**
   * Availability is why the counts are absent when they are, using the same
   * vocabulary as the profile endpoint.
   */
  availability: string;
  aces: number /* int16 */ | null;
  double_faults: number /* int16 */ | null;
  serve_points: number /* int16 */ | null;
  first_in: number /* int16 */ | null;
  first_won: number /* int16 */ | null;
  second_won: number /* int16 */ | null;
  serve_games: number /* int16 */ | null;
  break_points_saved: number /* int16 */ | null;
  break_points_faced: number /* int16 */ | null;
}

//////////
// source: players.go

/**
 * AvailabilityRecorded means every eligible match carried statistics.
 */
export const AvailabilityRecorded = "recorded";
/**
 * AvailabilityPartial means some did and some did not.
 */
export const AvailabilityPartial = "partial";
/**
 * AvailabilityNeverForTier means no match at this player's level has ever
 * recorded serve statistics — Futures and ITF, in any year.
 */
export const AvailabilityNeverForTier = "never_recorded_for_tier";
/**
 * AvailabilityNeverInEra means the matches predate the recording of them:
 * before 1991 anywhere, and before roughly 2010 at Challenger level.
 */
export const AvailabilityNeverInEra = "never_recorded_in_era";
/**
 * AvailabilityNotRecorded is the honest fallback: absent, reason unknown.
 */
export const AvailabilityNotRecorded = "not_recorded";
/**
 * PlayerProfile is the response for a single player.
 */
export interface PlayerProfile {
  slug: string;
  name: string;
  tour: string;
  country: string | null;
  hand: string | null;
  height_cm: number /* int16 */ | null;
  birth_date: string | null;
  pro_since: number /* int16 */ | null;
  /**
   * Career is null for a player with no ingested matches, which is not the
   * same as a career of zeroes.
   */
  career: Career | null;
  serve: ServeStats;
  /**
   * Ratings is null for a player nothing rated -- everyone whose only matches
   * were team events or walkovers. A series they never played is absent from
   * the list rather than sitting at the base rating.
   * tstype, because a nil slice marshals to null and the generated type
   * would otherwise promise an array that is sometimes not one.
   */
  ratings: SeriesRating[] | null;
}
/**
 * Career is the win/loss record. Retirements and walkovers are counted here and
 * excluded from every rate in Serve.
 */
export interface Career {
  matches: number /* int64 */;
  wins: number /* int64 */;
  losses: number /* int64 */;
  win_percentage: number /* float64 */;
  titles: number /* int64 */;
  /**
   * Majors are the subset of titles won at a Grand Slam. Eleven majors and
   * sixty-six titles are two different claims about the same career.
   */
  majors: number /* int64 */;
  incomplete_matches: number /* int64 */;
  first_match: string;
  last_match: string;
  surfaces: SurfaceSplit[];
  tiers: TierSplit[];
}
/**
 * SurfaceSplit is a win/loss record on one surface.
 */
export interface SurfaceSplit {
  surface: string;
  matches: number /* int64 */;
  wins: number /* int64 */;
  losses: number /* int64 */;
}
/**
 * TierSplit reports how many matches at a tier recorded statistics, which is
 * what makes "never recorded at this level" a checkable claim.
 */
export interface TierSplit {
  tier: string;
  matches: number /* int64 */;
  matches_with_stats: number /* int64 */;
}
/**
 * ServeStats carries the serve statistics, or the reason there are none.
 */
export interface ServeStats {
  availability: string;
  matches_with_data: number /* int64 */;
  rates: ServeRates | null;
}
/**
 * ServeRates are percentages and per-match averages. A nil field is a rate with
 * no denominator, which is different from a rate that is zero: a player who
 * never faced a break point has not saved 0% of them.
 */
export interface ServeRates {
  aces_per_match: number /* float64 */;
  double_faults_per_match: number /* float64 */;
  first_serve_in_percentage: number /* float64 */ | null;
  first_serve_won_percentage: number /* float64 */ | null;
  second_serve_won_percentage: number /* float64 */ | null;
  break_points_saved_percentage: number /* float64 */ | null;
}
/**
 * PlayerSearchResult is one row of the search response.
 */
export interface PlayerSearchResult {
  slug: string;
  name: string;
  tour: string;
  country: string | null;
  matches: number /* int64 */;
  best_tier: string | null;
  score: number /* float32 */;
}

//////////
// source: problem.go

/**
 * ProblemContentType is the media type RFC 7807 defines for error bodies.
 */
export const ProblemContentType = "application/problem+json";
/**
 * Problem is an RFC 7807 problem document. Every error this API returns is one
 * of these, so a client needs exactly one error shape.
 */
export interface Problem {
  /**
   * Type is a URI reference identifying the problem kind. Clients should
   * switch on this rather than on Title, which is for humans.
   */
  type: string;
  title: string;
  status: number /* int */;
  detail: string | null;
  instance: string | null;
  request_id: string | null;
}
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeNotFound = "/problems/not-found";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeBadRequest = "/problems/bad-request";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeRateLimited = "/problems/rate-limited";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeInternal = "/problems/internal";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeUnavailable = "/problems/unavailable";
/**
 * Problem types. These are URI references, not URLs to fetch: RFC 7807 does not
 * require them to resolve, and inventing a documentation host we do not own
 * would be worse than a stable relative reference.
 */
export const TypeMethodInvalid = "/problems/method-not-allowed";

//////////
// source: rankings.go

/**
 * RankingElo is this project's own rating.
 */
export const RankingElo = "elo";
/**
 * RankingOfficial is the list the tour publishes.
 */
export const RankingOfficial = "official";
/**
 * RankingRow is one player in a ranking.
 */
export interface RankingRow {
  /**
   * Position is where they stand in this list, which is not their official
   * rank and is not the same thing under the two types.
   */
  position: number /* int */;
  slug: string;
  name: string;
  tour: string;
  country: string | null;
  /**
   * Elo and OfficialRank are both here under both types, because the
   * comparison between them is the point of the page.
   */
  elo: number /* float64 */ | null;
  peak_elo: number /* float64 */ | null;
  official_rank: number /* int32 */ | null;
  points: number /* int32 */ | null;
  matches: number /* int32 */ | null;
  /**
   * Age at the effective date, null where no birth date was recorded.
   */
  age: number /* int */ | null;
  /**
   * Delta is how many places above or below their official rank the model
   * puts them. Null under the official type, where this list's position is
   * the official rank and the comparison would be with itself.
   */
  delta: number /* int */ | null;
}
/**
 * RankingPage is a page of a ranking, and the date it is a ranking as of.
 */
export interface RankingPage {
  type: string;
  surface: string | null;
  tour: string | null;
  /**
   * AsOf is the week actually used. Always the latest that exists at or
   * before what was asked for, never today.
   */
  as_of: string;
  /**
   * Requested is echoed only when it differed from AsOf, so a caller can see
   * that their date was moved and by how much.
   */
  requested: string | null;
  data: RankingRow[];
  next_cursor: string | null;
}

//////////
// source: ratings.go

/**
 * RatingPoint is one rating and the week it was taken.
 */
export interface RatingPoint {
  elo: number /* float64 */;
  as_of: string;
}
/**
 * SeriesRating is what a player is worth in one series.
 * Current and peak are both here because a page needs both: a player who
 * retired in 1983 has a current rating -- the last one they were given -- and
 * it is a real number that would be the wrong one to lead with.
 */
export interface SeriesRating {
  surface: string;
  /**
   * Matches is how many matches feed this series, which is what says whether
   * a surface rating is worth as much as the overall one.
   */
  matches: number /* int32 */;
  current: RatingPoint;
  peak: RatingPoint;
}
/**
 * RatingSeries is a whole trajectory, for a chart.
 */
export interface RatingSeries {
  surface: string;
  /**
   * From and To are the range actually covered, which is not the range asked
   * for: a player has ratings for the weeks they played and no others.
   */
  from: string;
  to: string;
  points: RatingPoint[];
}
/**
 * RankingPoint is one published ranking and the week it was published.
 */
export interface RankingPoint {
  date: string;
  rank: number /* int32 */;
  /**
   * Points is null for the decades before the tours published them, which is
   * not a week the player scored nothing.
   */
  points: number /* int32 */ | null;
}
/**
 * RankingHistory is the published ATP or WTA ranking over time, which is a
 * different claim from the Elo series beside it: one is what the tour said, the
 * other is what this project computes.
 */
export interface RankingHistory {
  from: string;
  to: string;
  best: RankingPoint | null;
  points: RankingPoint[];
}

//////////
// source: trajectory.go

/**
 * TrajectoryLine is one player's series.
 */
export interface TrajectoryLine {
  slug: string;
  name: string;
  /**
   * Position is where the player stands at the end of the window, which is
   * what decides whether a line is labelled or drawn as part of the field.
   */
  position: number /* int */;
  points: RatingPoint[];
}
/**
 * Trajectories is a multi-series chart's worth of data: one line per player
 * rather than one row per player, which is what a leaderboard is.
 */
export interface Trajectories {
  surface: string;
  tour: string | null;
  from: string;
  to: string;
  lines: TrajectoryLine[];
}
