// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coverage.sql

package db

import (
	"context"
	"time"
)

const getCoverage = `-- name: GetCoverage :many
SELECT t.tour,
       t.tier,
       count(*)::bigint                                     AS matches,
       min(m.played_on)::date                               AS first_match,
       max(m.played_on)::date                               AS last_match,
       count(*) FILTER (WHERE m.has_detailed_stats)::bigint AS matches_with_stats
  FROM matches m
  JOIN tournaments t ON t.id = m.tournament_id
 GROUP BY t.tour, t.tier
 ORDER BY t.tour, t.tier
`

type GetCoverageRow struct {
	Tour             Tour
	Tier             Tier
	Matches          int64
	FirstMatch       time.Time
	LastMatch        time.Time
	MatchesWithStats int64
}

// Coverage is queried, never declared. A "data current through" date written
// down somewhere drifts from the database the first time an ingest changes it;
// this cannot. See ADR-0006.
func (q *Queries) GetCoverage(ctx context.Context) ([]GetCoverageRow, error) {
	rows, err := q.db.Query(ctx, getCoverage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoverageRow{}
	for rows.Next() {
		var i GetCoverageRow
		if err := rows.Scan(
			&i.Tour,
			&i.Tier,
			&i.Matches,
			&i.FirstMatch,
			&i.LastMatch,
			&i.MatchesWithStats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
