// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const health = `-- name: Health :one
SELECT EXISTS (SELECT 1 FROM players) AS ready
`

// Touches a real table, so a database with no schema is distinguishable from
// a healthy one rather than both merely having an open socket.
func (q *Queries) Health(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, health)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}
