// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaders.sql

package db

import (
	"context"
)

const countLeaderPopulation = `-- name: CountLeaderPopulation :one
SELECT coalesce(sum(matches), 0)::bigint / 2 AS matches,
       coalesce(sum(with_stats), 0)::bigint / 2 AS with_stats,
       count(DISTINCT player_id)::bigint AS players
  FROM player_totals pt
 WHERE ($1::tour IS NULL OR pt.tour = $1::tour)
   AND ($2::tier IS NULL OR pt.tier = $2::tier)
   AND ($3::surface IS NULL OR pt.surface = $3::surface)
   AND ($4::smallint IS NULL OR pt.season = $4::smallint)
`

type CountLeaderPopulationParams struct {
	Tour    *Tour
	Tier    *Tier
	Surface *Surface
	Season  *int16
}

type CountLeaderPopulationRow struct {
	Matches   int32
	WithStats int32
	Players   int64
}

// What the board is a board of: matches under the filter, in matches rather
// than appearances, and how many of them the source recorded statistics for.
func (q *Queries) CountLeaderPopulation(ctx context.Context, arg CountLeaderPopulationParams) (CountLeaderPopulationRow, error) {
	row := q.db.QueryRow(ctx, countLeaderPopulation,
		arg.Tour,
		arg.Tier,
		arg.Surface,
		arg.Season,
	)
	var i CountLeaderPopulationRow
	err := row.Scan(&i.Matches, &i.WithStats, &i.Players)
	return i, err
}

const listLeaders = `-- name: ListLeaders :many
WITH totals AS (
    SELECT pt.player_id,
           sum(pt.matches)::bigint AS matches,
           sum(pt.wins)::bigint AS wins,
           sum(pt.with_serve)::bigint AS with_serve,
           sum(pt.aces)::bigint AS aces,
           sum(pt.double_faults)::bigint AS double_faults,
           sum(pt.serve_points)::bigint AS serve_points,
           sum(pt.first_in)::bigint AS first_in,
           sum(pt.first_won)::bigint AS first_won,
           sum(pt.second_won)::bigint AS second_won,
           sum(pt.serve_games)::bigint AS serve_games,
           sum(pt.bp_saved)::bigint AS bp_saved,
           sum(pt.bp_faced)::bigint AS bp_faced,
           sum(pt.with_return)::bigint AS with_return,
           sum(pt.op_serve_points)::bigint AS op_serve_points,
           sum(pt.op_first_in)::bigint AS op_first_in,
           sum(pt.op_first_won)::bigint AS op_first_won,
           sum(pt.op_second_won)::bigint AS op_second_won,
           sum(pt.op_serve_games)::bigint AS op_serve_games,
           sum(pt.op_bp_saved)::bigint AS op_bp_saved,
           sum(pt.op_bp_faced)::bigint AS op_bp_faced,
           sum(pt.scored)::bigint AS scored,
           sum(pt.sets_won)::bigint AS sets_won,
           sum(pt.sets_played)::bigint AS sets_played,
           sum(pt.games_won)::bigint AS games_won,
           sum(pt.games_played)::bigint AS games_played,
           sum(pt.tiebreaks_won)::bigint AS tiebreaks_won,
           sum(pt.tiebreaks_played)::bigint AS tiebreaks_played,
           sum(pt.deciders_won)::bigint AS deciders_won,
           sum(pt.deciders_played)::bigint AS deciders_played
      FROM player_totals pt
     WHERE ($3::tour IS NULL OR pt.tour = $3::tour)
       AND ($4::tier IS NULL OR pt.tier = $4::tier)
       AND ($5::surface IS NULL OR pt.surface = $5::surface)
       AND ($6::smallint IS NULL OR pt.season = $6::smallint)
       AND ($7::text IS NULL
            OR pt.player_id = (SELECT id FROM players WHERE slug = $7::text))
     GROUP BY pt.player_id
),
valued AS (
    SELECT t.player_id,
           CASE $8::text
               WHEN 'aces'                THEN t.aces
               WHEN 'double_faults'       THEN t.double_faults
               WHEN 'first_serve_in'      THEN t.first_in
               WHEN 'first_serve_won'     THEN t.first_won
               WHEN 'second_serve_won'    THEN t.second_won
               WHEN 'serve_points_won'    THEN t.first_won + t.second_won
               WHEN 'break_points_saved'  THEN t.bp_saved
               WHEN 'service_games_held'  THEN t.serve_games - (t.bp_faced - t.bp_saved)
               WHEN 'return_points_won'   THEN t.op_serve_points - t.op_first_won - t.op_second_won
               WHEN 'first_return_won'    THEN t.op_first_in - t.op_first_won
               WHEN 'second_return_won'   THEN (t.op_serve_points - t.op_first_in) - t.op_second_won
               WHEN 'break_points_won'    THEN t.op_bp_faced - t.op_bp_saved
               WHEN 'return_games_won'    THEN t.op_bp_faced - t.op_bp_saved
               WHEN 'points_won'          THEN (t.first_won + t.second_won) + (t.op_serve_points - t.op_first_won - t.op_second_won)
               WHEN 'matches_won'         THEN t.wins
               WHEN 'sets_won'            THEN t.sets_won
               WHEN 'games_won'           THEN t.games_won
               WHEN 'tiebreaks_won'       THEN t.tiebreaks_won
               WHEN 'deciding_sets_won'   THEN t.deciders_won
               ELSE 0
           END::bigint AS numerator,
           CASE $8::text
               WHEN 'aces'                THEN t.serve_points
               WHEN 'double_faults'       THEN t.serve_points
               WHEN 'first_serve_in'      THEN t.serve_points
               WHEN 'first_serve_won'     THEN t.first_in
               WHEN 'second_serve_won'    THEN t.serve_points - t.first_in
               WHEN 'serve_points_won'    THEN t.serve_points
               WHEN 'break_points_saved'  THEN t.bp_faced
               WHEN 'service_games_held'  THEN t.serve_games
               WHEN 'return_points_won'   THEN t.op_serve_points
               WHEN 'first_return_won'    THEN t.op_first_in
               WHEN 'second_return_won'   THEN t.op_serve_points - t.op_first_in
               WHEN 'break_points_won'    THEN t.op_bp_faced
               WHEN 'return_games_won'    THEN t.op_serve_games
               WHEN 'points_won'          THEN t.serve_points + t.op_serve_points
               WHEN 'matches_won'         THEN t.matches
               WHEN 'sets_won'            THEN t.sets_played
               WHEN 'games_won'           THEN t.games_played
               WHEN 'tiebreaks_won'       THEN t.tiebreaks_played
               WHEN 'deciding_sets_won'   THEN t.deciders_played
               ELSE 0
           END::bigint AS denominator,
           -- The dominance ratio is the one figure that is not a share of a
           -- count: return points won over serve points lost.
           CASE WHEN $8::text = 'dominance'
                     AND t.op_serve_points > 0 AND t.serve_points > 0
                     AND t.serve_points - t.first_won - t.second_won > 0
                THEN ((t.op_serve_points - t.op_first_won - t.op_second_won)::float8 / t.op_serve_points)
                     / ((t.serve_points - t.first_won - t.second_won)::float8 / t.serve_points)
           END::float8 AS ratio,
           CASE $8::text
               WHEN 'return_points_won'  THEN t.with_return
               WHEN 'first_return_won'   THEN t.with_return
               WHEN 'second_return_won'  THEN t.with_return
               WHEN 'break_points_won'   THEN t.with_return
               WHEN 'return_games_won'   THEN t.with_return
               WHEN 'points_won'         THEN least(t.with_serve, t.with_return)
               WHEN 'dominance'          THEN least(t.with_serve, t.with_return)
               WHEN 'matches_won'        THEN t.matches
               WHEN 'sets_won'           THEN t.scored
               WHEN 'games_won'          THEN t.scored
               WHEN 'tiebreaks_won'      THEN t.scored
               WHEN 'deciding_sets_won'  THEN t.scored
               ELSE t.with_serve
           END::bigint AS sample,
           t.matches
      FROM totals t
),
ranked AS (
    SELECT v.player_id, v.sample, v.matches, v.numerator, v.denominator,
           CASE WHEN $8::text = 'dominance' THEN v.ratio
                ELSE v.numerator::float8 / nullif(v.denominator, 0)
           END::float8 AS value
      FROM valued v
     WHERE v.sample >= $9::bigint
)
SELECT p.slug, p.full_name AS name, p.tour::text AS tour, p.country,
       r.sample, r.matches, r.numerator, r.denominator, r.value,
       count(*) OVER ()::bigint AS qualified
  FROM ranked r
  JOIN players p ON p.id = r.player_id
 WHERE r.value IS NOT NULL
 ORDER BY CASE WHEN $1::boolean THEN r.value END ASC,
          CASE WHEN NOT $1::boolean THEN r.value END DESC,
          r.sample DESC, p.slug
 LIMIT $2
`

type ListLeadersParams struct {
	Ascending  bool
	RowLimit   int32
	Tour       *Tour
	Tier       *Tier
	Surface    *Surface
	Season     *int16
	Player     *string
	Stat       string
	MinMatches int64
}

type ListLeadersRow struct {
	Slug        string
	Name        string
	Tour        string
	Country     *string
	Sample      int64
	Matches     int64
	Numerator   int64
	Denominator int64
	Value       float64
	Qualified   int64
}

// A leaderboard over player_totals: the filter is summed per player, the
// named stat is computed from its own numerator and denominator, and the
// rows are ranked on it. Every rate names the matches it stands on, in
// `sample`: the matches that carried this stat's inputs, which for a serve
// figure is the player's own serve lines, for a return figure the opponents',
// and for a figure read from the score the matches whose score was read.
//
// One query with the stat as a CASE rather than a query per stat, so the
// filter, the ranking and the denominators cannot drift between them. A
// player whose denominator is zero has no value and is not on the board.
// Ascending is for the one stat where less is better, double faults.
// `player` narrows the board to one player, so a page can say what an absent
// name's figure is and how many matches it stands on.
func (q *Queries) ListLeaders(ctx context.Context, arg ListLeadersParams) ([]ListLeadersRow, error) {
	rows, err := q.db.Query(ctx, listLeaders,
		arg.Ascending,
		arg.RowLimit,
		arg.Tour,
		arg.Tier,
		arg.Surface,
		arg.Season,
		arg.Player,
		arg.Stat,
		arg.MinMatches,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadersRow{}
	for rows.Next() {
		var i ListLeadersRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Tour,
			&i.Country,
			&i.Sample,
			&i.Matches,
			&i.Numerator,
			&i.Denominator,
			&i.Value,
			&i.Qualified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
