// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"
	"time"
)

const listPlayerMatches = `-- name: ListPlayerMatches :many
SELECT m.id,
       m.played_on,
       t.name                     AS tournament,
       t.tier,
       t.level,
       t.season,
       m.surface,
       m.round,
       m.is_qualifying,
       m.incomplete,
       m.score,
       m.minutes,
       mp.won,
       op.slug                    AS opponent_slug,
       op.full_name               AS opponent_name,
       mp.aces,
       mp.double_faults,
       mp.serve_points,
       mp.first_in,
       mp.first_won,
       mp.second_won,
       mp.serve_games,
       mp.bp_saved,
       mp.bp_faced
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  JOIN tournaments t ON t.id = m.tournament_id
  JOIN players op    ON op.id = CASE WHEN mp.won THEN m.loser_id ELSE m.winner_id END
 WHERE mp.player_id = $1
   AND ($2::surface IS NULL OR m.surface = $2::surface)
   AND ($3::tier IS NULL OR t.tier = $3::tier)
   AND ($4::smallint IS NULL OR t.season = $4::smallint)
   AND ($5::text IS NULL OR op.slug = $5::text)
   AND ($6::date IS NULL
        OR (m.played_on, m.id) < ($6::date, $7::bigint))
 ORDER BY m.played_on DESC, m.id DESC
 LIMIT $8
`

type ListPlayerMatchesParams struct {
	PlayerID  int64
	Surface   *Surface
	Tier      *Tier
	Season    *int16
	Opponent  *string
	AfterDate *time.Time
	AfterID   *int64
	RowLimit  int32
}

type ListPlayerMatchesRow struct {
	ID           int64
	PlayedOn     time.Time
	Tournament   string
	Tier         Tier
	Level        string
	Season       int16
	Surface      *Surface
	Round        string
	IsQualifying bool
	Incomplete   bool
	Score        *string
	Minutes      *int16
	Won          bool
	OpponentSlug string
	OpponentName string
	Aces         *int16
	DoubleFaults *int16
	ServePoints  *int16
	FirstIn      *int16
	FirstWon     *int16
	SecondWon    *int16
	ServeGames   *int16
	BpSaved      *int16
	BpFaced      *int16
}

// The list a player page is mostly made of. Most recent first, keyed on
// (played_on, id): played_on is a tournament's start date and so is nowhere
// near unique, and a cursor whose ordering key is not total repeats or skips
// rows. Both columns descend together, which is what makes the row-value
// comparison below valid here.
//
// The opponent comes from matches rather than a second pass over
// match_players: winner_id and loser_id are both NOT NULL and are half the
// match's natural key, so whichever is not this player is the other one.
func (q *Queries) ListPlayerMatches(ctx context.Context, arg ListPlayerMatchesParams) ([]ListPlayerMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerMatches,
		arg.PlayerID,
		arg.Surface,
		arg.Tier,
		arg.Season,
		arg.Opponent,
		arg.AfterDate,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerMatchesRow{}
	for rows.Next() {
		var i ListPlayerMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayedOn,
			&i.Tournament,
			&i.Tier,
			&i.Level,
			&i.Season,
			&i.Surface,
			&i.Round,
			&i.IsQualifying,
			&i.Incomplete,
			&i.Score,
			&i.Minutes,
			&i.Won,
			&i.OpponentSlug,
			&i.OpponentName,
			&i.Aces,
			&i.DoubleFaults,
			&i.ServePoints,
			&i.FirstIn,
			&i.FirstWon,
			&i.SecondWon,
			&i.ServeGames,
			&i.BpSaved,
			&i.BpFaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
