// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"
	"time"
)

const getChartedMatch = `-- name: GetChartedMatch :one
SELECT cm.charting_id,
       cm.played_on,
       cm.charted_by,
       t.name AS tournament,
       e.slug AS event_slug,
       t.season,
       m.round,
       m.score,
       w.slug AS winner_slug, w.full_name AS winner_name,
       l.slug AS loser_slug,  l.full_name AS loser_name,
       m.winner_id, m.loser_id
  FROM charted_matches cm
  JOIN matches m     ON m.id = cm.match_id
  JOIN tournaments t ON t.id = m.tournament_id
  LEFT JOIN events e ON e.id = t.event_id
  JOIN players w     ON w.id = m.winner_id
  JOIN players l     ON l.id = m.loser_id
 WHERE cm.charting_id = $1
`

type GetChartedMatchRow struct {
	ChartingID string
	PlayedOn   time.Time
	ChartedBy  *string
	Tournament string
	EventSlug  *string
	Season     int16
	Round      string
	Score      *string
	WinnerSlug string
	WinnerName string
	LoserSlug  string
	LoserName  string
	WinnerID   int64
	LoserID    int64
}

// The charted match by the project's own key, with the two players as the row
// names them: player 1 is the winner, player 2 the loser, and charted_stats
// is read per player so the sheet's columns follow.
func (q *Queries) GetChartedMatch(ctx context.Context, chartingID string) (GetChartedMatchRow, error) {
	row := q.db.QueryRow(ctx, getChartedMatch, chartingID)
	var i GetChartedMatchRow
	err := row.Scan(
		&i.ChartingID,
		&i.PlayedOn,
		&i.ChartedBy,
		&i.Tournament,
		&i.EventSlug,
		&i.Season,
		&i.Round,
		&i.Score,
		&i.WinnerSlug,
		&i.WinnerName,
		&i.LoserSlug,
		&i.LoserName,
		&i.WinnerID,
		&i.LoserID,
	)
	return i, err
}

const listChartedStats = `-- name: ListChartedStats :many
SELECT cs.player_id, cs.set_no,
       cs.serve_points, cs.aces, cs.double_faults, cs.first_in, cs.first_won,
       cs.second_in, cs.second_won, cs.bp_faced, cs.bp_saved,
       cs.return_points, cs.return_points_won,
       cs.winners, cs.winners_fh, cs.winners_bh, cs.unforced, cs.unforced_fh, cs.unforced_bh
  FROM charted_stats cs
  JOIN charted_matches cm ON cm.match_id = cs.match_id
 WHERE cm.charting_id = $1
 ORDER BY cs.set_no, cs.player_id
`

type ListChartedStatsRow struct {
	PlayerID        int64
	SetNo           int16
	ServePoints     int16
	Aces            int16
	DoubleFaults    int16
	FirstIn         int16
	FirstWon        int16
	SecondIn        int16
	SecondWon       int16
	BpFaced         int16
	BpSaved         int16
	ReturnPoints    int16
	ReturnPointsWon int16
	Winners         int16
	WinnersFh       int16
	WinnersBh       int16
	Unforced        int16
	UnforcedFh      int16
	UnforcedBh      int16
}

func (q *Queries) ListChartedStats(ctx context.Context, chartingID string) ([]ListChartedStatsRow, error) {
	rows, err := q.db.Query(ctx, listChartedStats, chartingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChartedStatsRow{}
	for rows.Next() {
		var i ListChartedStatsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.SetNo,
			&i.ServePoints,
			&i.Aces,
			&i.DoubleFaults,
			&i.FirstIn,
			&i.FirstWon,
			&i.SecondIn,
			&i.SecondWon,
			&i.BpFaced,
			&i.BpSaved,
			&i.ReturnPoints,
			&i.ReturnPointsWon,
			&i.Winners,
			&i.WinnersFh,
			&i.WinnersBh,
			&i.Unforced,
			&i.UnforcedFh,
			&i.UnforcedBh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeadToHeadMeetings = `-- name: ListHeadToHeadMeetings :many
SELECT m.id,
       m.played_on,
       t.name  AS tournament,
       e.slug  AS event_slug,
       t.tier,
       t.level,
       t.season,
       m.surface,
       m.round,
       m.is_qualifying,
       m.incomplete,
       m.score,
       m.winner_id,
       m.best_of,
       m.deciding_set,
       m.tiebreaks_winner,
       m.tiebreaks_loser,
       a.aces AS a_aces, a.double_faults AS a_double_faults, a.serve_points AS a_serve_points,
       a.first_in AS a_first_in, a.first_won AS a_first_won, a.second_won AS a_second_won,
       a.bp_saved AS a_bp_saved, a.bp_faced AS a_bp_faced,
       b.aces AS b_aces, b.double_faults AS b_double_faults, b.serve_points AS b_serve_points,
       b.first_in AS b_first_in, b.first_won AS b_first_won, b.second_won AS b_second_won,
       b.bp_saved AS b_bp_saved, b.bp_faced AS b_bp_faced,
       cm.charting_id
  FROM matches m
  JOIN tournaments t   ON t.id = m.tournament_id
  LEFT JOIN events e   ON e.id = t.event_id
  LEFT JOIN charted_matches cm ON cm.match_id = m.id
  JOIN match_players a ON a.match_id = m.id AND a.player_id = $1
  JOIN match_players b ON b.match_id = m.id AND b.player_id = $2
 WHERE (m.winner_id = $1 AND m.loser_id = $2)
    OR (m.winner_id = $2 AND m.loser_id = $1)
 ORDER BY m.played_on, m.id
`

type ListHeadToHeadMeetingsParams struct {
	PlayerA int64
	PlayerB int64
}

type ListHeadToHeadMeetingsRow struct {
	ID              int64
	PlayedOn        time.Time
	Tournament      string
	EventSlug       *string
	Tier            Tier
	Level           string
	Season          int16
	Surface         *Surface
	Round           string
	IsQualifying    bool
	Incomplete      bool
	Score           *string
	WinnerID        int64
	BestOf          int16
	DecidingSet     *bool
	TiebreaksWinner *int16
	TiebreaksLoser  *int16
	AAces           *int16
	ADoubleFaults   *int16
	AServePoints    *int16
	AFirstIn        *int16
	AFirstWon       *int16
	ASecondWon      *int16
	ABpSaved        *int16
	ABpFaced        *int16
	BAces           *int16
	BDoubleFaults   *int16
	BServePoints    *int16
	BFirstIn        *int16
	BFirstWon       *int16
	BSecondWon      *int16
	BBpSaved        *int16
	BBpFaced        *int16
	ChartingID      *string
}

// Every match the two have played, oldest first, with both serve lines.
//
// One query rather than an aggregate per split: even the longest rivalry in the
// database is a few dozen rows, and counting them in Go keeps the record, the
// surface split and the tier split from being three chances to disagree.
//
// Ordered oldest to newest because that is how a rivalry reads.
func (q *Queries) ListHeadToHeadMeetings(ctx context.Context, arg ListHeadToHeadMeetingsParams) ([]ListHeadToHeadMeetingsRow, error) {
	rows, err := q.db.Query(ctx, listHeadToHeadMeetings, arg.PlayerA, arg.PlayerB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeadToHeadMeetingsRow{}
	for rows.Next() {
		var i ListHeadToHeadMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayedOn,
			&i.Tournament,
			&i.EventSlug,
			&i.Tier,
			&i.Level,
			&i.Season,
			&i.Surface,
			&i.Round,
			&i.IsQualifying,
			&i.Incomplete,
			&i.Score,
			&i.WinnerID,
			&i.BestOf,
			&i.DecidingSet,
			&i.TiebreaksWinner,
			&i.TiebreaksLoser,
			&i.AAces,
			&i.ADoubleFaults,
			&i.AServePoints,
			&i.AFirstIn,
			&i.AFirstWon,
			&i.ASecondWon,
			&i.ABpSaved,
			&i.ABpFaced,
			&i.BAces,
			&i.BDoubleFaults,
			&i.BServePoints,
			&i.BFirstIn,
			&i.BFirstWon,
			&i.BSecondWon,
			&i.BBpSaved,
			&i.BBpFaced,
			&i.ChartingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerMatches = `-- name: ListPlayerMatches :many
SELECT m.id,
       m.played_on,
       t.name                     AS tournament,
       e.slug                     AS event_slug,
       t.tier,
       t.level,
       t.season,
       m.surface,
       m.round,
       m.is_qualifying,
       m.incomplete,
       m.score,
       m.minutes,
       mp.won,
       op.slug                    AS opponent_slug,
       op.full_name               AS opponent_name,
       mp.aces,
       mp.double_faults,
       mp.serve_points,
       mp.first_in,
       mp.first_won,
       mp.second_won,
       mp.serve_games,
       mp.bp_saved,
       mp.bp_faced,
       cm.charting_id
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  LEFT JOIN charted_matches cm ON cm.match_id = m.id
  JOIN tournaments t ON t.id = m.tournament_id
  LEFT JOIN events e ON e.id = t.event_id
  JOIN players op    ON op.id = CASE WHEN mp.won THEN m.loser_id ELSE m.winner_id END
 WHERE mp.player_id = $1
   AND ($2::surface IS NULL OR m.surface = $2::surface)
   AND ($3::tier IS NULL OR t.tier = $3::tier)
   AND ($4::smallint IS NULL OR t.season = $4::smallint)
   AND ($5::text IS NULL OR op.slug = $5::text)
   AND ($6::date IS NULL
        OR (m.played_on, m.id) < ($6::date, $7::bigint))
 ORDER BY m.played_on DESC, m.id DESC
 LIMIT $8
`

type ListPlayerMatchesParams struct {
	PlayerID  int64
	Surface   *Surface
	Tier      *Tier
	Season    *int16
	Opponent  *string
	AfterDate *time.Time
	AfterID   *int64
	RowLimit  int32
}

type ListPlayerMatchesRow struct {
	ID           int64
	PlayedOn     time.Time
	Tournament   string
	EventSlug    *string
	Tier         Tier
	Level        string
	Season       int16
	Surface      *Surface
	Round        string
	IsQualifying bool
	Incomplete   bool
	Score        *string
	Minutes      *int16
	Won          bool
	OpponentSlug string
	OpponentName string
	Aces         *int16
	DoubleFaults *int16
	ServePoints  *int16
	FirstIn      *int16
	FirstWon     *int16
	SecondWon    *int16
	ServeGames   *int16
	BpSaved      *int16
	BpFaced      *int16
	ChartingID   *string
}

// The list a player page is mostly made of. Most recent first, keyed on
// (played_on, id): played_on is a tournament's start date and so is nowhere
// near unique, and a cursor whose ordering key is not total repeats or skips
// rows. Both columns descend together, which is what makes the row-value
// comparison below valid here.
//
// The opponent comes from matches rather than a second pass over
// match_players: winner_id and loser_id are both NOT NULL and are half the
// match's natural key, so whichever is not this player is the other one.
func (q *Queries) ListPlayerMatches(ctx context.Context, arg ListPlayerMatchesParams) ([]ListPlayerMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerMatches,
		arg.PlayerID,
		arg.Surface,
		arg.Tier,
		arg.Season,
		arg.Opponent,
		arg.AfterDate,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerMatchesRow{}
	for rows.Next() {
		var i ListPlayerMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayedOn,
			&i.Tournament,
			&i.EventSlug,
			&i.Tier,
			&i.Level,
			&i.Season,
			&i.Surface,
			&i.Round,
			&i.IsQualifying,
			&i.Incomplete,
			&i.Score,
			&i.Minutes,
			&i.Won,
			&i.OpponentSlug,
			&i.OpponentName,
			&i.Aces,
			&i.DoubleFaults,
			&i.ServePoints,
			&i.FirstIn,
			&i.FirstWon,
			&i.SecondWon,
			&i.ServeGames,
			&i.BpSaved,
			&i.BpFaced,
			&i.ChartingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
