// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"
	"time"
)

const listHeadToHeadMeetings = `-- name: ListHeadToHeadMeetings :many
SELECT m.id,
       m.played_on,
       t.name  AS tournament,
       t.tier,
       t.level,
       t.season,
       m.surface,
       m.round,
       m.is_qualifying,
       m.incomplete,
       m.score,
       m.winner_id,
       a.aces AS a_aces, a.double_faults AS a_double_faults, a.serve_points AS a_serve_points,
       a.first_in AS a_first_in, a.first_won AS a_first_won, a.second_won AS a_second_won,
       a.bp_saved AS a_bp_saved, a.bp_faced AS a_bp_faced,
       b.aces AS b_aces, b.double_faults AS b_double_faults, b.serve_points AS b_serve_points,
       b.first_in AS b_first_in, b.first_won AS b_first_won, b.second_won AS b_second_won,
       b.bp_saved AS b_bp_saved, b.bp_faced AS b_bp_faced
  FROM matches m
  JOIN tournaments t   ON t.id = m.tournament_id
  JOIN match_players a ON a.match_id = m.id AND a.player_id = $1
  JOIN match_players b ON b.match_id = m.id AND b.player_id = $2
 WHERE (m.winner_id = $1 AND m.loser_id = $2)
    OR (m.winner_id = $2 AND m.loser_id = $1)
 ORDER BY m.played_on, m.id
`

type ListHeadToHeadMeetingsParams struct {
	PlayerA int64
	PlayerB int64
}

type ListHeadToHeadMeetingsRow struct {
	ID            int64
	PlayedOn      time.Time
	Tournament    string
	Tier          Tier
	Level         string
	Season        int16
	Surface       *Surface
	Round         string
	IsQualifying  bool
	Incomplete    bool
	Score         *string
	WinnerID      int64
	AAces         *int16
	ADoubleFaults *int16
	AServePoints  *int16
	AFirstIn      *int16
	AFirstWon     *int16
	ASecondWon    *int16
	ABpSaved      *int16
	ABpFaced      *int16
	BAces         *int16
	BDoubleFaults *int16
	BServePoints  *int16
	BFirstIn      *int16
	BFirstWon     *int16
	BSecondWon    *int16
	BBpSaved      *int16
	BBpFaced      *int16
}

// Every match the two have played, oldest first, with both serve lines.
//
// One query rather than an aggregate per split: even the longest rivalry in the
// database is a few dozen rows, and counting them in Go keeps the record, the
// surface split and the tier split from being three chances to disagree.
//
// Ordered oldest to newest because that is how a rivalry reads.
func (q *Queries) ListHeadToHeadMeetings(ctx context.Context, arg ListHeadToHeadMeetingsParams) ([]ListHeadToHeadMeetingsRow, error) {
	rows, err := q.db.Query(ctx, listHeadToHeadMeetings, arg.PlayerA, arg.PlayerB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeadToHeadMeetingsRow{}
	for rows.Next() {
		var i ListHeadToHeadMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayedOn,
			&i.Tournament,
			&i.Tier,
			&i.Level,
			&i.Season,
			&i.Surface,
			&i.Round,
			&i.IsQualifying,
			&i.Incomplete,
			&i.Score,
			&i.WinnerID,
			&i.AAces,
			&i.ADoubleFaults,
			&i.AServePoints,
			&i.AFirstIn,
			&i.AFirstWon,
			&i.ASecondWon,
			&i.ABpSaved,
			&i.ABpFaced,
			&i.BAces,
			&i.BDoubleFaults,
			&i.BServePoints,
			&i.BFirstIn,
			&i.BFirstWon,
			&i.BSecondWon,
			&i.BBpSaved,
			&i.BBpFaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerMatches = `-- name: ListPlayerMatches :many
SELECT m.id,
       m.played_on,
       t.name                     AS tournament,
       t.tier,
       t.level,
       t.season,
       m.surface,
       m.round,
       m.is_qualifying,
       m.incomplete,
       m.score,
       m.minutes,
       mp.won,
       op.slug                    AS opponent_slug,
       op.full_name               AS opponent_name,
       mp.aces,
       mp.double_faults,
       mp.serve_points,
       mp.first_in,
       mp.first_won,
       mp.second_won,
       mp.serve_games,
       mp.bp_saved,
       mp.bp_faced
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  JOIN tournaments t ON t.id = m.tournament_id
  JOIN players op    ON op.id = CASE WHEN mp.won THEN m.loser_id ELSE m.winner_id END
 WHERE mp.player_id = $1
   AND ($2::surface IS NULL OR m.surface = $2::surface)
   AND ($3::tier IS NULL OR t.tier = $3::tier)
   AND ($4::smallint IS NULL OR t.season = $4::smallint)
   AND ($5::text IS NULL OR op.slug = $5::text)
   AND ($6::date IS NULL
        OR (m.played_on, m.id) < ($6::date, $7::bigint))
 ORDER BY m.played_on DESC, m.id DESC
 LIMIT $8
`

type ListPlayerMatchesParams struct {
	PlayerID  int64
	Surface   *Surface
	Tier      *Tier
	Season    *int16
	Opponent  *string
	AfterDate *time.Time
	AfterID   *int64
	RowLimit  int32
}

type ListPlayerMatchesRow struct {
	ID           int64
	PlayedOn     time.Time
	Tournament   string
	Tier         Tier
	Level        string
	Season       int16
	Surface      *Surface
	Round        string
	IsQualifying bool
	Incomplete   bool
	Score        *string
	Minutes      *int16
	Won          bool
	OpponentSlug string
	OpponentName string
	Aces         *int16
	DoubleFaults *int16
	ServePoints  *int16
	FirstIn      *int16
	FirstWon     *int16
	SecondWon    *int16
	ServeGames   *int16
	BpSaved      *int16
	BpFaced      *int16
}

// The list a player page is mostly made of. Most recent first, keyed on
// (played_on, id): played_on is a tournament's start date and so is nowhere
// near unique, and a cursor whose ordering key is not total repeats or skips
// rows. Both columns descend together, which is what makes the row-value
// comparison below valid here.
//
// The opponent comes from matches rather than a second pass over
// match_players: winner_id and loser_id are both NOT NULL and are half the
// match's natural key, so whichever is not this player is the other one.
func (q *Queries) ListPlayerMatches(ctx context.Context, arg ListPlayerMatchesParams) ([]ListPlayerMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerMatches,
		arg.PlayerID,
		arg.Surface,
		arg.Tier,
		arg.Season,
		arg.Opponent,
		arg.AfterDate,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerMatchesRow{}
	for rows.Next() {
		var i ListPlayerMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayedOn,
			&i.Tournament,
			&i.Tier,
			&i.Level,
			&i.Season,
			&i.Surface,
			&i.Round,
			&i.IsQualifying,
			&i.Incomplete,
			&i.Score,
			&i.Minutes,
			&i.Won,
			&i.OpponentSlug,
			&i.OpponentName,
			&i.Aces,
			&i.DoubleFaults,
			&i.ServePoints,
			&i.FirstIn,
			&i.FirstWon,
			&i.SecondWon,
			&i.ServeGames,
			&i.BpSaved,
			&i.BpFaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
