// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Hand string

const (
	HandR Hand = "R"
	HandL Hand = "L"
	HandU Hand = "U"
)

func (e *Hand) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Hand(s)
	case string:
		*e = Hand(s)
	default:
		return fmt.Errorf("unsupported scan type for Hand: %T", src)
	}
	return nil
}

type NullHand struct {
	Hand  Hand
	Valid bool // Valid is true if Hand is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHand) Scan(value interface{}) error {
	if value == nil {
		ns.Hand, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Hand.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHand) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Hand), nil
}

type RatingSurface string

const (
	RatingSurfaceOverall RatingSurface = "overall"
	RatingSurfaceHard    RatingSurface = "hard"
	RatingSurfaceClay    RatingSurface = "clay"
	RatingSurfaceGrass   RatingSurface = "grass"
	RatingSurfaceCarpet  RatingSurface = "carpet"
)

func (e *RatingSurface) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RatingSurface(s)
	case string:
		*e = RatingSurface(s)
	default:
		return fmt.Errorf("unsupported scan type for RatingSurface: %T", src)
	}
	return nil
}

type NullRatingSurface struct {
	RatingSurface RatingSurface
	Valid         bool // Valid is true if RatingSurface is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRatingSurface) Scan(value interface{}) error {
	if value == nil {
		ns.RatingSurface, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RatingSurface.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRatingSurface) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RatingSurface), nil
}

type Surface string

const (
	SurfaceHard   Surface = "hard"
	SurfaceClay   Surface = "clay"
	SurfaceGrass  Surface = "grass"
	SurfaceCarpet Surface = "carpet"
)

func (e *Surface) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Surface(s)
	case string:
		*e = Surface(s)
	default:
		return fmt.Errorf("unsupported scan type for Surface: %T", src)
	}
	return nil
}

type NullSurface struct {
	Surface Surface
	Valid   bool // Valid is true if Surface is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSurface) Scan(value interface{}) error {
	if value == nil {
		ns.Surface, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Surface.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSurface) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Surface), nil
}

type Tier string

const (
	TierTour       Tier = "tour"
	TierChallenger Tier = "challenger"
	TierFutures    Tier = "futures"
	TierItf        Tier = "itf"
)

func (e *Tier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Tier(s)
	case string:
		*e = Tier(s)
	default:
		return fmt.Errorf("unsupported scan type for Tier: %T", src)
	}
	return nil
}

type NullTier struct {
	Tier  Tier
	Valid bool // Valid is true if Tier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTier) Scan(value interface{}) error {
	if value == nil {
		ns.Tier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Tier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Tier), nil
}

type Tour string

const (
	TourAtp Tour = "atp"
	TourWta Tour = "wta"
)

func (e *Tour) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Tour(s)
	case string:
		*e = Tour(s)
	default:
		return fmt.Errorf("unsupported scan type for Tour: %T", src)
	}
	return nil
}

type NullTour struct {
	Tour  Tour
	Valid bool // Valid is true if Tour is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTour) Scan(value interface{}) error {
	if value == nil {
		ns.Tour, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Tour.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTour) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Tour), nil
}

type IngestRun struct {
	ID          int64
	Source      string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	RowsSeen    *int32
	RowsWritten *int32
	Error       *string
}

type Match struct {
	ID               int64
	TournamentID     int64
	MatchNum         int16
	Round            string
	BestOf           int16
	Surface          *Surface
	Score            *string
	Minutes          *int16
	WinnerID         int64
	PlayedOn         time.Time
	Incomplete       bool
	IsQualifying     bool
	IsTeamEvent      bool
	HasDetailedStats bool
	Indoor           *bool
	Source           string
}

type MatchPlayer struct {
	MatchID      int64
	PlayerID     int64
	Won          bool
	Seed         *int16
	Entry        *string
	Rank         *int32
	RankPoints   *int32
	Age          pgtype.Numeric
	Aces         *int16
	DoubleFaults *int16
	ServePoints  *int16
	FirstIn      *int16
	FirstWon     *int16
	SecondWon    *int16
	ServeGames   *int16
	BpSaved      *int16
	BpFaced      *int16
}

type Player struct {
	ID         int64
	SourceID   string
	Tour       Tour
	Slug       string
	FullName   string
	FirstName  *string
	LastName   *string
	Country    *string
	Hand       *Hand
	HeightCm   *int16
	BirthDate  *time.Time
	ProSince   *int16
	WikidataID *string
}

type PlayerAlias struct {
	Source     string
	SourceID   string
	PlayerID   int64
	Confidence pgtype.Numeric
}

type Ranking struct {
	PlayerID    int64
	RankingDate time.Time
	Rank        int32
	Points      *int32
}

type Rating struct {
	PlayerID      int64
	AsOf          time.Time
	Surface       RatingSurface
	Elo           pgtype.Numeric
	MatchesPlayed int32
}

type Tournament struct {
	ID        int64
	SourceID  string
	Tour      Tour
	Name      string
	Level     string
	Tier      Tier
	Surface   *Surface
	DrawSize  *int16
	StartDate time.Time
	Season    int16
}
