// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ongoing.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOngoingMatches = `-- name: DeleteOngoingMatches :exec
DELETE FROM ongoing_matches WHERE file = $1
`

func (q *Queries) DeleteOngoingMatches(ctx context.Context, file string) error {
	_, err := q.db.Exec(ctx, deleteOngoingMatches, file)
	return err
}

const getOngoingFile = `-- name: GetOngoingFile :one
SELECT file, etag, checked_at, changed_at, rows FROM ongoing_files WHERE file = $1
`

func (q *Queries) GetOngoingFile(ctx context.Context, file string) (OngoingFile, error) {
	row := q.db.QueryRow(ctx, getOngoingFile, file)
	var i OngoingFile
	err := row.Scan(
		&i.File,
		&i.Etag,
		&i.CheckedAt,
		&i.ChangedAt,
		&i.Rows,
	)
	return i, err
}

const insertOngoingMatch = `-- name: InsertOngoingMatch :exec
INSERT INTO ongoing_matches (file, tour, tourney_source_id, tourney_name, level, surface, indoor,
                             match_num, round, played_on, score,
                             winner_source_id, winner_name, winner_seed,
                             loser_source_id, loser_name, loser_seed)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11,
        $12, $13, $14,
        $15, $16, $17)
`

type InsertOngoingMatchParams struct {
	File            string
	Tour            Tour
	TourneySourceID string
	TourneyName     string
	Level           string
	Surface         *Surface
	Indoor          *bool
	MatchNum        int32
	Round           string
	PlayedOn        time.Time
	Score           *string
	WinnerSourceID  string
	WinnerName      string
	WinnerSeed      *int16
	LoserSourceID   string
	LoserName       string
	LoserSeed       *int16
}

func (q *Queries) InsertOngoingMatch(ctx context.Context, arg InsertOngoingMatchParams) error {
	_, err := q.db.Exec(ctx, insertOngoingMatch,
		arg.File,
		arg.Tour,
		arg.TourneySourceID,
		arg.TourneyName,
		arg.Level,
		arg.Surface,
		arg.Indoor,
		arg.MatchNum,
		arg.Round,
		arg.PlayedOn,
		arg.Score,
		arg.WinnerSourceID,
		arg.WinnerName,
		arg.WinnerSeed,
		arg.LoserSourceID,
		arg.LoserName,
		arg.LoserSeed,
	)
	return err
}

const listOngoingFiles = `-- name: ListOngoingFiles :many
SELECT file, checked_at, changed_at, rows FROM ongoing_files ORDER BY file
`

type ListOngoingFilesRow struct {
	File      string
	CheckedAt pgtype.Timestamptz
	ChangedAt pgtype.Timestamptz
	Rows      int32
}

func (q *Queries) ListOngoingFiles(ctx context.Context) ([]ListOngoingFilesRow, error) {
	rows, err := q.db.Query(ctx, listOngoingFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOngoingFilesRow{}
	for rows.Next() {
		var i ListOngoingFilesRow
		if err := rows.Scan(
			&i.File,
			&i.CheckedAt,
			&i.ChangedAt,
			&i.Rows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingMatches = `-- name: ListOngoingMatches :many
SELECT o.tour, o.tourney_source_id, o.tourney_name, o.level, o.surface, o.indoor,
       o.match_num, o.round, o.played_on, o.score,
       o.winner_name, o.winner_seed, coalesce(w.slug, '') AS winner_slug,
       o.loser_name, o.loser_seed, coalesce(l.slug, '') AS loser_slug
  FROM ongoing_matches o
  LEFT JOIN LATERAL (
        SELECT p.slug FROM players p
         WHERE (p.source_id = o.winner_source_id AND p.tour = o.tour)
            OR p.id = (SELECT a.player_id FROM player_aliases a
                        WHERE a.source_id = o.winner_source_id AND a.source LIKE 'tml-%'
                        LIMIT 1)
         LIMIT 1) w ON true
  LEFT JOIN LATERAL (
        SELECT p.slug FROM players p
         WHERE (p.source_id = o.loser_source_id AND p.tour = o.tour)
            OR p.id = (SELECT a.player_id FROM player_aliases a
                        WHERE a.source_id = o.loser_source_id AND a.source LIKE 'tml-%'
                        LIMIT 1)
         LIMIT 1) l ON true
 ORDER BY o.tour, o.tourney_name, o.played_on DESC, o.match_num DESC
`

type ListOngoingMatchesRow struct {
	Tour            Tour
	TourneySourceID string
	TourneyName     string
	Level           string
	Surface         *Surface
	Indoor          *bool
	MatchNum        int32
	Round           string
	PlayedOn        time.Time
	Score           *string
	WinnerName      string
	WinnerSeed      *int16
	WinnerSlug      string
	LoserName       string
	LoserSeed       *int16
	LoserSlug       string
}

// Every provisional result, with a player's slug where the database knows the
// source id: directly for a player first seen in these files, through an alias
// for one the older files named differently.
func (q *Queries) ListOngoingMatches(ctx context.Context) ([]ListOngoingMatchesRow, error) {
	rows, err := q.db.Query(ctx, listOngoingMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOngoingMatchesRow{}
	for rows.Next() {
		var i ListOngoingMatchesRow
		if err := rows.Scan(
			&i.Tour,
			&i.TourneySourceID,
			&i.TourneyName,
			&i.Level,
			&i.Surface,
			&i.Indoor,
			&i.MatchNum,
			&i.Round,
			&i.PlayedOn,
			&i.Score,
			&i.WinnerName,
			&i.WinnerSeed,
			&i.WinnerSlug,
			&i.LoserName,
			&i.LoserSeed,
			&i.LoserSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOngoingFile = `-- name: SaveOngoingFile :exec
INSERT INTO ongoing_files (file, etag, checked_at, changed_at, rows)
VALUES ($1, $2, now(), now(), $3)
ON CONFLICT (file) DO UPDATE
   SET checked_at = now(),
       etag       = CASE WHEN $4::boolean THEN EXCLUDED.etag ELSE ongoing_files.etag END,
       changed_at = CASE WHEN $4::boolean THEN now() ELSE ongoing_files.changed_at END,
       rows       = CASE WHEN $4::boolean THEN EXCLUDED.rows ELSE ongoing_files.rows END
`

type SaveOngoingFileParams struct {
	File    string
	Etag    *string
	Rows    int32
	Changed bool
}

// changed is false for a 304: the file was asked for and had not moved.
func (q *Queries) SaveOngoingFile(ctx context.Context, arg SaveOngoingFileParams) error {
	_, err := q.db.Exec(ctx, saveOngoingFile,
		arg.File,
		arg.Etag,
		arg.Rows,
		arg.Changed,
	)
	return err
}
