// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"time"
)

const getPlayerBySlug = `-- name: GetPlayerBySlug :one
SELECT id, slug, tour, full_name, first_name, last_name, country, hand,
       height_cm, birth_date, pro_since, wikidata_id
  FROM players
 WHERE slug = $1
`

type GetPlayerBySlugRow struct {
	ID         int64
	Slug       string
	Tour       Tour
	FullName   string
	FirstName  *string
	LastName   *string
	Country    *string
	Hand       *Hand
	HeightCm   *int16
	BirthDate  *time.Time
	ProSince   *int16
	WikidataID *string
}

func (q *Queries) GetPlayerBySlug(ctx context.Context, slug string) (GetPlayerBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPlayerBySlug, slug)
	var i GetPlayerBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Tour,
		&i.FullName,
		&i.FirstName,
		&i.LastName,
		&i.Country,
		&i.Hand,
		&i.HeightCm,
		&i.BirthDate,
		&i.ProSince,
		&i.WikidataID,
	)
	return i, err
}

const getPlayerCareerSummary = `-- name: GetPlayerCareerSummary :one
WITH played AS (
    SELECT mp.won, mp.aces, mp.double_faults, mp.serve_points, mp.first_in,
           mp.first_won, mp.second_won, mp.serve_games, mp.bp_saved, mp.bp_faced,
           m.incomplete, m.round, m.is_qualifying, m.played_on, t.level
      FROM match_players mp
      JOIN matches m     ON m.id = mp.match_id
      JOIN tournaments t ON t.id = m.tournament_id
     WHERE mp.player_id = $1
),
counted AS (
    SELECT count(*)::bigint                             AS matches,
           count(*) FILTER (WHERE won)::bigint          AS wins,
           count(*) FILTER (WHERE NOT won)::bigint      AS losses,
           -- Retirements and walkovers count here but are excluded from rates.
           count(*) FILTER (WHERE incomplete)::bigint   AS incomplete_matches,
           count(*) FILTER (WHERE won AND round = 'F' AND NOT is_qualifying)::bigint AS titles,
           -- Majors are titles at level G. Counted separately because 11 majors
           -- and 66 titles are two different claims about the same career.
           count(*) FILTER (WHERE won AND round = 'F' AND NOT is_qualifying
                              AND level = 'G')::bigint AS majors,
           min(played_on)::date                         AS first_match,
           max(played_on)::date                         AS last_match
      FROM played
    -- No matches means no career summary at all. Returning a row of
    -- NULLs instead would not survive the scan.
    HAVING count(*) > 0
),
served AS (
    SELECT count(*)::bigint         AS stat_matches,
           coalesce(sum(aces), 0)::bigint        AS aces,
           coalesce(sum(double_faults), 0)::bigint AS double_faults,
           coalesce(sum(serve_points), 0)::bigint  AS serve_points,
           coalesce(sum(first_in), 0)::bigint      AS first_in,
           coalesce(sum(first_won), 0)::bigint     AS first_won,
           coalesce(sum(second_won), 0)::bigint    AS second_won,
           coalesce(sum(serve_games), 0)::bigint   AS serve_games,
           coalesce(sum(bp_saved), 0)::bigint      AS bp_saved,
           coalesce(sum(bp_faced), 0)::bigint      AS bp_faced
      FROM played
     WHERE serve_points IS NOT NULL AND NOT incomplete
)
SELECT matches, wins, losses, incomplete_matches, titles, majors, first_match, last_match, stat_matches, aces, double_faults, serve_points, first_in, first_won, second_won, serve_games, bp_saved, bp_faced FROM counted, served
`

type GetPlayerCareerSummaryRow struct {
	Matches           int64
	Wins              int64
	Losses            int64
	IncompleteMatches int64
	Titles            int64
	Majors            int64
	FirstMatch        time.Time
	LastMatch         time.Time
	StatMatches       int64
	Aces              int64
	DoubleFaults      int64
	ServePoints       int64
	FirstIn           int64
	FirstWon          int64
	SecondWon         int64
	ServeGames        int64
	BpSaved           int64
	BpFaced           int64
}

// Rate statistics come from a separate aggregate over only the matches that
// recorded them: a NULL sum with stat_matches = 0 means never recorded, which
// the response must not collapse into a zero.
func (q *Queries) GetPlayerCareerSummary(ctx context.Context, playerID int64) (GetPlayerCareerSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPlayerCareerSummary, playerID)
	var i GetPlayerCareerSummaryRow
	err := row.Scan(
		&i.Matches,
		&i.Wins,
		&i.Losses,
		&i.IncompleteMatches,
		&i.Titles,
		&i.Majors,
		&i.FirstMatch,
		&i.LastMatch,
		&i.StatMatches,
		&i.Aces,
		&i.DoubleFaults,
		&i.ServePoints,
		&i.FirstIn,
		&i.FirstWon,
		&i.SecondWon,
		&i.ServeGames,
		&i.BpSaved,
		&i.BpFaced,
	)
	return i, err
}

const getPlayerClutch = `-- name: GetPlayerClutch :one
WITH played AS (
    SELECT t.tour,
           t.tier,
           ((t.season / 10) * 10)::smallint                   AS decade,
           count(*)                                           AS appearances,
           count(*) FILTER (WHERE m.deciding_set IS NOT NULL) AS scored,
           coalesce(sum(mp.bp_saved), 0)                      AS bp_saved,
           coalesce(sum(mp.bp_faced), 0)                      AS bp_faced,
           coalesce(sum(CASE WHEN mp.won THEN m.tiebreaks_winner
                                         ELSE m.tiebreaks_loser END), 0) AS tiebreaks_won,
           coalesce(sum(m.tiebreaks_winner + m.tiebreaks_loser), 0)      AS tiebreaks_played,
           count(*) FILTER (WHERE m.deciding_set AND mp.won)  AS deciding_sets_won,
           count(*) FILTER (WHERE m.deciding_set)             AS deciding_sets_played
      FROM match_players mp
      JOIN matches m     ON m.id = mp.match_id
      JOIN tournaments t ON t.id = m.tournament_id
     WHERE mp.player_id = $1
       AND NOT m.is_team_event
     GROUP BY 1, 2, 3
)
SELECT
    coalesce(sum(p.appearances), 0)::bigint          AS appearances,
    coalesce(sum(p.scored), 0)::bigint               AS scored,
    coalesce(sum(p.bp_saved), 0)::bigint             AS bp_saved,
    coalesce(sum(p.bp_faced), 0)::bigint             AS bp_faced,
    coalesce(sum(p.tiebreaks_won), 0)::bigint        AS tiebreaks_won,
    coalesce(sum(p.tiebreaks_played), 0)::bigint     AS tiebreaks_played,
    coalesce(sum(p.deciding_sets_won), 0)::bigint    AS deciding_sets_won,
    coalesce(sum(p.deciding_sets_played), 0)::bigint AS deciding_sets_played,
    -- Each baseline is the player's own opportunities in a cell against what
    -- the tour did in that cell. A cell where either side had no opportunities
    -- of that kind leaves both the numerator and the denominator, so it cannot
    -- drag the average toward a rate nobody recorded.
    -- Weight of zero is how "no baseline" arrives: a rate over no opportunities
    -- would be a comparison against nothing, and 0.0 would look like one
    -- against something.
    coalesce(sum(p.bp_faced * b.bp_saved::float8 / b.bp_faced)
        FILTER (WHERE b.bp_faced > 0 AND p.bp_faced > 0), 0)::float8      AS baseline_bp_weighted,
    coalesce(sum(p.bp_faced)
        FILTER (WHERE b.bp_faced > 0 AND p.bp_faced > 0), 0)::bigint      AS baseline_bp_weight,
    coalesce(sum(p.tiebreaks_played * b.tiebreaks_won::float8 / b.tiebreaks_played)
        FILTER (WHERE b.tiebreaks_played > 0 AND p.tiebreaks_played > 0), 0)::float8 AS baseline_tiebreaks_weighted,
    coalesce(sum(p.tiebreaks_played)
        FILTER (WHERE b.tiebreaks_played > 0 AND p.tiebreaks_played > 0), 0)::bigint AS baseline_tiebreaks_weight,
    coalesce(sum(p.deciding_sets_played * b.deciding_sets_won::float8 / b.deciding_sets_played)
        FILTER (WHERE b.deciding_sets_played > 0 AND p.deciding_sets_played > 0), 0)::float8 AS baseline_deciding_weighted,
    coalesce(sum(p.deciding_sets_played)
        FILTER (WHERE b.deciding_sets_played > 0 AND p.deciding_sets_played > 0), 0)::bigint AS baseline_deciding_weight,
    -- What the comparison is against, so the response can state it rather than
    -- leaving a reader to assume it.
    coalesce(min(p.decade), 0)::smallint              AS from_decade,
    coalesce(max(p.decade), 0)::smallint              AS to_decade,
    coalesce(sum(b.appearances), 0)::bigint          AS baseline_appearances,
    array_remove(array_agg(DISTINCT p.tier::text), NULL)::text[] AS tiers
  FROM played p
  LEFT JOIN clutch_baselines b
         ON b.tour = p.tour AND b.tier = p.tier AND b.decade = p.decade
`

type GetPlayerClutchRow struct {
	Appearances               int64
	Scored                    int64
	BpSaved                   int64
	BpFaced                   int64
	TiebreaksWon              int64
	TiebreaksPlayed           int64
	DecidingSetsWon           int64
	DecidingSetsPlayed        int64
	BaselineBpWeighted        float64
	BaselineBpWeight          int64
	BaselineTiebreaksWeighted float64
	BaselineTiebreaksWeight   int64
	BaselineDecidingWeighted  float64
	BaselineDecidingWeight    int64
	FromDecade                int16
	ToDecade                  int16
	BaselineAppearances       int64
	Tiers                     []string
}

// Under pressure, measured against the tour over the same levels and years.
//
// The baseline is weighted by where this player's own opportunities actually
// fell. A career that spans Futures in the 1990s and tour level in the 2020s is
// compared with what the tour did across that same spread, rather than against
// one era it only half belongs to -- which is the judgement the issue said had
// to be made and stated.
//
// Both halves are read from columns the ingest derived. Neither the score
// parsing nor a 1.6 million match aggregate belongs in a request.
func (q *Queries) GetPlayerClutch(ctx context.Context, playerID int64) (GetPlayerClutchRow, error) {
	row := q.db.QueryRow(ctx, getPlayerClutch, playerID)
	var i GetPlayerClutchRow
	err := row.Scan(
		&i.Appearances,
		&i.Scored,
		&i.BpSaved,
		&i.BpFaced,
		&i.TiebreaksWon,
		&i.TiebreaksPlayed,
		&i.DecidingSetsWon,
		&i.DecidingSetsPlayed,
		&i.BaselineBpWeighted,
		&i.BaselineBpWeight,
		&i.BaselineTiebreaksWeighted,
		&i.BaselineTiebreaksWeight,
		&i.BaselineDecidingWeighted,
		&i.BaselineDecidingWeight,
		&i.FromDecade,
		&i.ToDecade,
		&i.BaselineAppearances,
		&i.Tiers,
	)
	return i, err
}

const getPlayerLastTourMatch = `-- name: GetPlayerLastTourMatch :one
SELECT m.played_on
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  JOIN tournaments t ON t.id = m.tournament_id
 WHERE mp.player_id = $1
   AND t.tier = 'tour'
   AND NOT m.is_qualifying AND NOT m.incomplete AND NOT m.is_team_event
 ORDER BY m.played_on DESC
 LIMIT 1
`

// The end of the window a player's percentiles are read over: their last
// finished main-draw match at tour level, so a retired player is measured
// against the tour they last played on rather than today's.
func (q *Queries) GetPlayerLastTourMatch(ctx context.Context, playerID int64) (time.Time, error) {
	row := q.db.QueryRow(ctx, getPlayerLastTourMatch, playerID)
	var played_on time.Time
	err := row.Scan(&played_on)
	return played_on, err
}

const getPlayerOpponentQuality = `-- name: GetPlayerOpponentQuality :one
WITH faced AS (
    SELECT mp.won, oe.elo::float8 AS elo
      FROM match_players mp
      JOIN matches m ON m.id = mp.match_id
      JOIN LATERAL (
            SELECT r.elo
              FROM ratings r
             WHERE r.player_id = CASE WHEN mp.won THEN m.loser_id ELSE m.winner_id END
               AND r.surface = 'overall'
               AND r.as_of <= m.played_on
             ORDER BY r.as_of DESC
             LIMIT 1) oe ON true
     WHERE mp.player_id = $2
       AND NOT m.is_team_event AND NOT m.incomplete
)
SELECT count(*)::bigint                                          AS rated_matches,
       coalesce(avg(elo), 0)::float8                             AS average_elo,
       coalesce(max(elo), 0)::float8                             AS highest_elo,
       count(*) FILTER (WHERE elo >= $1::float8)::bigint AS elite_matches,
       count(*) FILTER (WHERE elo >= $1::float8 AND won)::bigint AS elite_wins
  FROM faced
`

type GetPlayerOpponentQualityParams struct {
	EliteElo float64
	PlayerID int64
}

type GetPlayerOpponentQualityRow struct {
	RatedMatches int64
	AverageElo   float64
	HighestElo   float64
	EliteMatches int64
	EliteWins    int64
}

// What the schedule was worth: the Elo every opponent held on the day, averaged,
// and the record against the ones above a bar. A match whose opponent the model
// had not rated yet is left out of both rather than counted at the base rating.
func (q *Queries) GetPlayerOpponentQuality(ctx context.Context, arg GetPlayerOpponentQualityParams) (GetPlayerOpponentQualityRow, error) {
	row := q.db.QueryRow(ctx, getPlayerOpponentQuality, arg.EliteElo, arg.PlayerID)
	var i GetPlayerOpponentQualityRow
	err := row.Scan(
		&i.RatedMatches,
		&i.AverageElo,
		&i.HighestElo,
		&i.EliteMatches,
		&i.EliteWins,
	)
	return i, err
}

const getPlayerRatings = `-- name: GetPlayerRatings :many
WITH latest AS (
    SELECT DISTINCT ON (r.surface) r.surface, r.elo, r.as_of, r.matches_played
      FROM ratings r
     WHERE r.player_id = $1
     ORDER BY r.surface, r.as_of DESC
),
peak AS (
    SELECT DISTINCT ON (r.surface) r.surface, r.elo, r.as_of
      FROM ratings r
     WHERE r.player_id = $1
     ORDER BY r.surface, r.elo DESC, r.as_of
)
SELECT l.surface,
       l.matches_played,
       l.elo::float8   AS current_elo,
       l.as_of         AS current_as_of,
       p.elo::float8   AS peak_elo,
       p.as_of         AS peak_as_of
  FROM latest l
  JOIN peak p ON p.surface = l.surface
 ORDER BY (l.surface <> 'overall'), l.matches_played DESC, l.surface
`

type GetPlayerRatingsRow struct {
	Surface       RatingSurface
	MatchesPlayed int32
	CurrentElo    float64
	CurrentAsOf   time.Time
	PeakElo       float64
	PeakAsOf      time.Time
}

// Current and peak per series, in one pass over the player's rows.
//
// The table is sparse -- a row exists only for a week a series moved -- so
// "current" is the last row, not a row at any particular date, and there is no
// date on which every series has one.
//
// Ordered overall first and then by how much play backs each surface, which is
// the order the surface strip reads in.
func (q *Queries) GetPlayerRatings(ctx context.Context, playerID int64) ([]GetPlayerRatingsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerRatings, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerRatingsRow{}
	for rows.Next() {
		var i GetPlayerRatingsRow
		if err := rows.Scan(
			&i.Surface,
			&i.MatchesPlayed,
			&i.CurrentElo,
			&i.CurrentAsOf,
			&i.PeakElo,
			&i.PeakAsOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerReturnSummary = `-- name: GetPlayerReturnSummary :one
WITH played AS (
    SELECT mp.serve_points   AS own_points,
           mp.first_won      AS own_first_won,
           mp.second_won     AS own_second_won,
           op.serve_points,
           op.first_in,
           op.first_won,
           op.second_won,
           op.serve_games,
           op.bp_saved,
           op.bp_faced
      FROM match_players mp
      JOIN matches m       ON m.id = mp.match_id
      JOIN match_players op ON op.match_id = m.id AND op.player_id <> mp.player_id
     WHERE mp.player_id = $1
       AND NOT m.incomplete
)
SELECT count(*) FILTER (WHERE serve_points IS NOT NULL)::bigint       AS stat_matches,
       coalesce(sum(serve_points), 0)::bigint                         AS serve_points,
       coalesce(sum(first_in), 0)::bigint                             AS first_in,
       coalesce(sum(first_won), 0)::bigint                            AS first_won,
       coalesce(sum(second_won), 0)::bigint                           AS second_won,
       coalesce(sum(serve_games), 0)::bigint                          AS serve_games,
       coalesce(sum(bp_saved), 0)::bigint                             AS bp_saved,
       coalesce(sum(bp_faced), 0)::bigint                             AS bp_faced,
       count(*) FILTER (WHERE serve_points IS NOT NULL
                          AND own_points IS NOT NULL)::bigint         AS both_matches,
       coalesce(sum(own_points) FILTER (WHERE serve_points IS NOT NULL), 0)::bigint     AS own_serve_points,
       coalesce(sum(own_first_won) FILTER (WHERE serve_points IS NOT NULL), 0)::bigint  AS own_first_won,
       coalesce(sum(own_second_won) FILTER (WHERE serve_points IS NOT NULL), 0)::bigint AS own_second_won
  FROM played
`

type GetPlayerReturnSummaryRow struct {
	StatMatches    int64
	ServePoints    int64
	FirstIn        int64
	FirstWon       int64
	SecondWon      int64
	ServeGames     int64
	BpSaved        int64
	BpFaced        int64
	BothMatches    int64
	OwnServePoints int64
	OwnFirstWon    int64
	OwnSecondWon   int64
}

// The other half of a career. A return figure is made of the opponent's serve
// line, never of the player's own, so it is counted over the matches that
// carried the opponent's line -- which is not always the same set as the ones
// that carried this player's. Both denominators are reported so neither rate
// borrows the other's.
//
// The last three columns are the player's own serve line over the subset where
// both sides were recorded, because total points won and the dominance ratio
// are quotients of the two and a match with only one line would bias them.
func (q *Queries) GetPlayerReturnSummary(ctx context.Context, playerID int64) (GetPlayerReturnSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPlayerReturnSummary, playerID)
	var i GetPlayerReturnSummaryRow
	err := row.Scan(
		&i.StatMatches,
		&i.ServePoints,
		&i.FirstIn,
		&i.FirstWon,
		&i.SecondWon,
		&i.ServeGames,
		&i.BpSaved,
		&i.BpFaced,
		&i.BothMatches,
		&i.OwnServePoints,
		&i.OwnFirstWon,
		&i.OwnSecondWon,
	)
	return i, err
}

const getPlayerSurfaceSplits = `-- name: GetPlayerSurfaceSplits :many
SELECT m.surface,
       count(*)::bigint                            AS matches,
       count(*) FILTER (WHERE mp.won)::bigint      AS wins,
       count(*) FILTER (WHERE NOT mp.won)::bigint  AS losses
  FROM match_players mp
  JOIN matches m ON m.id = mp.match_id
 WHERE mp.player_id = $1
 GROUP BY m.surface
 ORDER BY matches DESC
`

type GetPlayerSurfaceSplitsRow struct {
	Surface *Surface
	Matches int64
	Wins    int64
	Losses  int64
}

func (q *Queries) GetPlayerSurfaceSplits(ctx context.Context, playerID int64) ([]GetPlayerSurfaceSplitsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerSurfaceSplits, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerSurfaceSplitsRow{}
	for rows.Next() {
		var i GetPlayerSurfaceSplitsRow
		if err := rows.Scan(
			&i.Surface,
			&i.Matches,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTierSplits = `-- name: GetPlayerTierSplits :many
SELECT t.tier,
       count(*)::bigint                                       AS matches,
       count(*) FILTER (WHERE m.has_detailed_stats)::bigint   AS matches_with_stats
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  JOIN tournaments t ON t.id = m.tournament_id
 WHERE mp.player_id = $1
 GROUP BY t.tier
 ORDER BY matches DESC
`

type GetPlayerTierSplitsRow struct {
	Tier             Tier
	Matches          int64
	MatchesWithStats int64
}

// Which tiers a player competed at, so the API can say a statistic was never
// recorded for their level rather than implying it was zero.
func (q *Queries) GetPlayerTierSplits(ctx context.Context, playerID int64) ([]GetPlayerTierSplitsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerTierSplits, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerTierSplitsRow{}
	for rows.Next() {
		var i GetPlayerTierSplitsRow
		if err := rows.Scan(&i.Tier, &i.Matches, &i.MatchesWithStats); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerBestWins = `-- name: ListPlayerBestWins :many
SELECT m.played_on,
       t.name        AS tournament,
       e.slug        AS event_slug,
       t.season,
       t.level,
       t.tier,
       m.surface,
       m.round,
       m.score,
       op.slug       AS opponent_slug,
       op.full_name  AS opponent_name,
       op.country    AS opponent_country,
       oe.elo::float8 AS opponent_elo,
       oe.as_of      AS elo_as_of
  FROM match_players mp
  JOIN matches m      ON m.id = mp.match_id
  JOIN tournaments t  ON t.id = m.tournament_id
  LEFT JOIN events e  ON e.id = t.event_id
  JOIN players op     ON op.id = m.loser_id
  JOIN LATERAL (
        SELECT r.elo, r.as_of
          FROM ratings r
         WHERE r.player_id = m.loser_id
           AND r.surface = 'overall'
           AND r.as_of <= m.played_on
         ORDER BY r.as_of DESC
         LIMIT 1) oe ON true
 WHERE mp.player_id = $1
   AND mp.won
   AND NOT m.incomplete AND NOT m.is_team_event AND NOT m.is_qualifying
 ORDER BY oe.elo DESC, m.played_on DESC
 LIMIT $2
`

type ListPlayerBestWinsParams struct {
	PlayerID int64
	RowLimit int32
}

type ListPlayerBestWinsRow struct {
	PlayedOn        time.Time
	Tournament      string
	EventSlug       *string
	Season          int16
	Level           string
	Tier            Tier
	Surface         *Surface
	Round           string
	Score           *string
	OpponentSlug    string
	OpponentName    string
	OpponentCountry *string
	OpponentElo     float64
	EloAsOf         time.Time
}

// The wins that cost the most to get: every opponent carries the overall Elo
// they held on the day, read from the last weekly snapshot on or before the
// match, and the list is ordered on it.
//
// Rating the opponent as they were rather than as they ended keeps a win over
// a future champion from being credited with the champion's peak.
func (q *Queries) ListPlayerBestWins(ctx context.Context, arg ListPlayerBestWinsParams) ([]ListPlayerBestWinsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerBestWins, arg.PlayerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerBestWinsRow{}
	for rows.Next() {
		var i ListPlayerBestWinsRow
		if err := rows.Scan(
			&i.PlayedOn,
			&i.Tournament,
			&i.EventSlug,
			&i.Season,
			&i.Level,
			&i.Tier,
			&i.Surface,
			&i.Round,
			&i.Score,
			&i.OpponentSlug,
			&i.OpponentName,
			&i.OpponentCountry,
			&i.OpponentElo,
			&i.EloAsOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerFinalsByCategory = `-- name: ListPlayerFinalsByCategory :many
SELECT CASE
           WHEN t.level = 'D' OR t.event_link = 'team' THEN 'team'
           WHEN t.level = 'G' THEN 'slam'
           WHEN t.level = 'F' THEN 'finals'
           WHEN t.level = 'O' THEN 'olympics'
           WHEN t.level IN ('M', 'PM', '1000') THEN 'masters'
           ELSE t.tier::text
       END::text                               AS category,
       count(*)::bigint                        AS finals,
       count(*) FILTER (WHERE mp.won)::bigint  AS titles
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  JOIN tournaments t ON t.id = m.tournament_id
 WHERE mp.player_id = $1
   AND m.round = 'F' AND NOT m.is_qualifying
 GROUP BY 1
 ORDER BY titles DESC, finals DESC, category
`

type ListPlayerFinalsByCategoryRow struct {
	Category string
	Finals   int64
	Titles   int64
}

// Titles and finals by what the event was, in the same words the season index
// uses, so a slam title and a Challenger title are never one number.
func (q *Queries) ListPlayerFinalsByCategory(ctx context.Context, playerID int64) ([]ListPlayerFinalsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listPlayerFinalsByCategory, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerFinalsByCategoryRow{}
	for rows.Next() {
		var i ListPlayerFinalsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Finals, &i.Titles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerOpponentRanks = `-- name: ListPlayerOpponentRanks :many
SELECT mp.won, mp.rank AS own_rank, op.rank AS opponent_rank, m.score, m.deciding_set
  FROM match_players mp
  JOIN matches m ON m.id = mp.match_id
  JOIN match_players op ON op.match_id = m.id AND op.player_id <> mp.player_id
 WHERE mp.player_id = $1
   AND NOT m.incomplete AND NOT m.is_team_event
`

type ListPlayerOpponentRanksRow struct {
	Won          bool
	OwnRank      *int32
	OpponentRank *int32
	Score        *string
	DecidingSet  *bool
}

// Every finished, non-team match of one player with the ranking each side
// held on the day, for the record by opponent rank, and the score and
// deciding-set flag for the matches decided by a final-set tiebreak. A few
// hundred rows for a long career, bucketed in Go.
func (q *Queries) ListPlayerOpponentRanks(ctx context.Context, playerID int64) ([]ListPlayerOpponentRanksRow, error) {
	rows, err := q.db.Query(ctx, listPlayerOpponentRanks, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerOpponentRanksRow{}
	for rows.Next() {
		var i ListPlayerOpponentRanksRow
		if err := rows.Scan(
			&i.Won,
			&i.OwnRank,
			&i.OpponentRank,
			&i.Score,
			&i.DecidingSet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRankingHistory = `-- name: ListPlayerRankingHistory :many
SELECT ranking_date, rank, points
  FROM rankings
 WHERE player_id = $1
   AND ($2::date IS NULL OR ranking_date >= $2::date)
   AND ($3::date IS NULL OR ranking_date <= $3::date)
 ORDER BY ranking_date
`

type ListPlayerRankingHistoryParams struct {
	PlayerID int64
	FromDate *time.Time
	ToDate   *time.Time
}

type ListPlayerRankingHistoryRow struct {
	RankingDate time.Time
	Rank        int32
	Points      *int32
}

// The published ATP/WTA ranking over time. Not paginated, for the same reason
// the rating series is not: a line is not read a page at a time.
func (q *Queries) ListPlayerRankingHistory(ctx context.Context, arg ListPlayerRankingHistoryParams) ([]ListPlayerRankingHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRankingHistory, arg.PlayerID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRankingHistoryRow{}
	for rows.Next() {
		var i ListPlayerRankingHistoryRow
		if err := rows.Scan(&i.RankingDate, &i.Rank, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRatingSeries = `-- name: ListPlayerRatingSeries :many
SELECT as_of, elo::float8 AS elo, matches_played
  FROM ratings
 WHERE player_id = $1
   AND surface = $2::rating_surface
   AND ($3::date IS NULL OR as_of >= $3::date)
   AND ($4::date IS NULL OR as_of <= $4::date)
 ORDER BY as_of
`

type ListPlayerRatingSeriesParams struct {
	PlayerID int64
	Surface  RatingSurface
	FromDate *time.Time
	ToDate   *time.Time
}

type ListPlayerRatingSeriesRow struct {
	AsOf          time.Time
	Elo           float64
	MatchesPlayed int32
}

// The whole trajectory for one series. Not paginated: a chart wants the line,
// and a page of a line is not one.
func (q *Queries) ListPlayerRatingSeries(ctx context.Context, arg ListPlayerRatingSeriesParams) ([]ListPlayerRatingSeriesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRatingSeries,
		arg.PlayerID,
		arg.Surface,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRatingSeriesRow{}
	for rows.Next() {
		var i ListPlayerRatingSeriesRow
		if err := rows.Scan(&i.AsOf, &i.Elo, &i.MatchesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRivals = `-- name: ListPlayerRivals :many
SELECT op.slug,
       op.full_name         AS name,
       op.country,
       count(*)::bigint     AS matches,
       count(*) FILTER (WHERE mp.won)::bigint AS wins,
       max(m.played_on)::date AS last_played
  FROM match_players mp
  JOIN matches m  ON m.id = mp.match_id
  JOIN players op ON op.id = CASE WHEN mp.won THEN m.loser_id ELSE m.winner_id END
 WHERE mp.player_id = $1
   AND NOT m.is_team_event
 GROUP BY op.slug, op.full_name, op.country
 ORDER BY matches DESC, last_played DESC, op.full_name
 LIMIT $2
`

type ListPlayerRivalsParams struct {
	PlayerID int64
	RowLimit int32
}

type ListPlayerRivalsRow struct {
	Slug       string
	Name       string
	Country    *string
	Matches    int64
	Wins       int64
	LastPlayed time.Time
}

// Who a career was spent against. Ordered on meetings rather than on the
// record, because the question a rivalry list answers is who kept turning up.
func (q *Queries) ListPlayerRivals(ctx context.Context, arg ListPlayerRivalsParams) ([]ListPlayerRivalsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRivals, arg.PlayerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRivalsRow{}
	for rows.Next() {
		var i ListPlayerRivalsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Country,
			&i.Matches,
			&i.Wins,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRoundRecord = `-- name: ListPlayerRoundRecord :many
SELECT m.round,
       count(*)::bigint                        AS matches,
       count(*) FILTER (WHERE mp.won)::bigint  AS wins
  FROM match_players mp
  JOIN matches m ON m.id = mp.match_id
 WHERE mp.player_id = $1
   AND NOT m.is_team_event AND NOT m.is_qualifying AND NOT m.incomplete
 GROUP BY m.round
`

type ListPlayerRoundRecordRow struct {
	Round   string
	Matches int64
	Wins    int64
}

// How far a career got, round by round. Qualifying is excluded: reaching the
// second round of qualifying and the second round of a draw are not the same
// achievement and must not be summed into one row.
func (q *Queries) ListPlayerRoundRecord(ctx context.Context, playerID int64) ([]ListPlayerRoundRecordRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRoundRecord, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRoundRecordRow{}
	for rows.Next() {
		var i ListPlayerRoundRecordRow
		if err := rows.Scan(&i.Round, &i.Matches, &i.Wins); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerSeasonTotals = `-- name: ListPlayerSeasonTotals :many
SELECT season,
       sum(matches)::bigint AS matches,
       sum(wins)::bigint AS wins,
       sum(titles)::bigint AS titles,
       sum(with_serve)::bigint AS with_serve,
       sum(aces)::bigint AS aces,
       sum(double_faults)::bigint AS double_faults,
       sum(serve_points)::bigint AS serve_points,
       sum(first_won)::bigint AS first_won,
       sum(second_won)::bigint AS second_won,
       sum(serve_games)::bigint AS serve_games,
       sum(bp_saved)::bigint AS bp_saved,
       sum(bp_faced)::bigint AS bp_faced,
       sum(with_return)::bigint AS with_return,
       sum(op_serve_points)::bigint AS op_serve_points,
       sum(op_first_won)::bigint AS op_first_won,
       sum(op_second_won)::bigint AS op_second_won,
       sum(op_serve_games)::bigint AS op_serve_games,
       sum(op_bp_saved)::bigint AS op_bp_saved,
       sum(op_bp_faced)::bigint AS op_bp_faced,
       sum(scored)::bigint AS scored,
       sum(sets_won)::bigint AS sets_won,
       sum(sets_played)::bigint AS sets_played,
       sum(games_won)::bigint AS games_won,
       sum(games_played)::bigint AS games_played,
       sum(tiebreaks_won)::bigint AS tiebreaks_won,
       sum(tiebreaks_played)::bigint AS tiebreaks_played,
       sum(deciders_won)::bigint AS deciders_won,
       sum(deciders_played)::bigint AS deciders_played
  FROM player_totals
 WHERE player_id = $1
 GROUP BY season
 ORDER BY season
`

type ListPlayerSeasonTotalsRow struct {
	Season          int16
	Matches         int64
	Wins            int64
	Titles          int64
	WithServe       int64
	Aces            int64
	DoubleFaults    int64
	ServePoints     int64
	FirstWon        int64
	SecondWon       int64
	ServeGames      int64
	BpSaved         int64
	BpFaced         int64
	WithReturn      int64
	OpServePoints   int64
	OpFirstWon      int64
	OpSecondWon     int64
	OpServeGames    int64
	OpBpSaved       int64
	OpBpFaced       int64
	Scored          int64
	SetsWon         int64
	SetsPlayed      int64
	GamesWon        int64
	GamesPlayed     int64
	TiebreaksWon    int64
	TiebreaksPlayed int64
	DecidersWon     int64
	DecidersPlayed  int64
}

// One player's year-by-year, summed from player_totals across tier and
// surface. Totals, so the page computes every rate over its own count of
// matches: a season with four recorded matches and sixty played must not
// read as a season of four.
func (q *Queries) ListPlayerSeasonTotals(ctx context.Context, playerID int64) ([]ListPlayerSeasonTotalsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerSeasonTotals, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerSeasonTotalsRow{}
	for rows.Next() {
		var i ListPlayerSeasonTotalsRow
		if err := rows.Scan(
			&i.Season,
			&i.Matches,
			&i.Wins,
			&i.Titles,
			&i.WithServe,
			&i.Aces,
			&i.DoubleFaults,
			&i.ServePoints,
			&i.FirstWon,
			&i.SecondWon,
			&i.ServeGames,
			&i.BpSaved,
			&i.BpFaced,
			&i.WithReturn,
			&i.OpServePoints,
			&i.OpFirstWon,
			&i.OpSecondWon,
			&i.OpServeGames,
			&i.OpBpSaved,
			&i.OpBpFaced,
			&i.Scored,
			&i.SetsWon,
			&i.SetsPlayed,
			&i.GamesWon,
			&i.GamesPlayed,
			&i.TiebreaksWon,
			&i.TiebreaksPlayed,
			&i.DecidersWon,
			&i.DecidersPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerStreaks = `-- name: ListPlayerStreaks :many
WITH played AS (
    SELECT m.played_on, m.id, mp.won,
           row_number() OVER (ORDER BY m.played_on, m.id)
         - row_number() OVER (PARTITION BY mp.won ORDER BY m.played_on, m.id) AS run
      FROM match_players mp
      JOIN matches m ON m.id = mp.match_id
     WHERE mp.player_id = $1
       AND NOT m.is_team_event AND NOT m.incomplete
),
runs AS (
    SELECT won,
           count(*)::bigint     AS length,
           min(played_on)::date AS from_date,
           max(played_on)::date AS to_date,
           max(id)              AS last_id
      FROM played
     GROUP BY won, run
),
best AS (
    SELECT won, length, from_date, to_date, last_id FROM runs WHERE won ORDER BY length DESC, to_date DESC LIMIT 1
),
worst AS (
    SELECT won, length, from_date, to_date, last_id FROM runs WHERE NOT won ORDER BY length DESC, to_date DESC LIMIT 1
),
latest AS (
    SELECT won, length, from_date, to_date, last_id FROM runs ORDER BY to_date DESC, last_id DESC LIMIT 1
)
SELECT 'best'::text AS kind, won, length, from_date, to_date FROM best
UNION ALL
SELECT 'worst'::text AS kind, won, length, from_date, to_date FROM worst
UNION ALL
SELECT 'current'::text AS kind, won, length, from_date, to_date FROM latest
`

type ListPlayerStreaksRow struct {
	Kind     string
	Won      bool
	Length   int64
	FromDate time.Time
	ToDate   time.Time
}

// Gaps and islands over one career: the difference between a row's position in
// the whole sequence and its position among rows of the same result is constant
// inside a run and changes at every switch, so grouping on it groups the runs.
//
// Retirements and walkovers are left out: a run of wins broken by an opponent
// who never came out has not been broken by a defeat. Team events are out for
// the same reason Elo leaves them out.
//
// Up to three labelled rows rather than one row of nullable columns: a career
// with no defeat has no worst run, and that is a row that is not there rather
// than a run of length zero.
func (q *Queries) ListPlayerStreaks(ctx context.Context, playerID int64) ([]ListPlayerStreaksRow, error) {
	rows, err := q.db.Query(ctx, listPlayerStreaks, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerStreaksRow{}
	for rows.Next() {
		var i ListPlayerStreaksRow
		if err := rows.Scan(
			&i.Kind,
			&i.Won,
			&i.Length,
			&i.FromDate,
			&i.ToDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServeBaselines = `-- name: ListServeBaselines :many
SELECT tier::text AS tier, surface::text AS surface, decade, serve_points, serve_won
  FROM serve_baselines
 WHERE tour = $1::tour
 ORDER BY tier, surface, decade
`

type ListServeBaselinesRow struct {
	Tier        string
	Surface     string
	Decade      int16
	ServePoints int64
	ServeWon    int64
}

// Every serve-baseline cell for one tour, for the anchor lookup in
// internal/simulate.
//
// The whole tour rather than one cell, because the lookup widens when a cell is
// thin and a widening query would be four round trips or one query nobody can
// read. There are at most a few hundred rows per tour.
func (q *Queries) ListServeBaselines(ctx context.Context, tour Tour) ([]ListServeBaselinesRow, error) {
	rows, err := q.db.Query(ctx, listServeBaselines, tour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServeBaselinesRow{}
	for rows.Next() {
		var i ListServeBaselinesRow
		if err := rows.Scan(
			&i.Tier,
			&i.Surface,
			&i.Decade,
			&i.ServePoints,
			&i.ServeWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTourWindowTotals = `-- name: ListTourWindowTotals :many
WITH lines AS (
    SELECT mp.player_id, mp.won, t.level, op.rank AS opponent_rank,
           mp.serve_points IS NOT NULL AND op.serve_points IS NOT NULL AS has_stats,
           mp.serve_points, mp.first_won, mp.second_won, mp.bp_saved, mp.bp_faced,
           op.serve_points AS op_serve_points, op.first_won AS op_first_won,
           op.second_won AS op_second_won, op.bp_saved AS op_bp_saved,
           op.bp_faced AS op_bp_faced,
           CASE WHEN mp.won THEN m.tiebreaks_winner ELSE m.tiebreaks_loser END AS tiebreaks_won,
           m.tiebreaks_winner + m.tiebreaks_loser AS tiebreaks_played,
           m.deciding_set
      FROM matches m
      JOIN tournaments t    ON t.id = m.tournament_id
      JOIN match_players mp ON mp.match_id = m.id
      JOIN match_players op ON op.match_id = m.id AND op.player_id <> mp.player_id
     WHERE t.tour = $1::tour AND t.tier = 'tour'
       AND NOT m.is_qualifying AND NOT m.incomplete AND NOT m.is_team_event
       AND m.played_on > $2::date AND m.played_on <= $3::date
)
SELECT player_id,
       count(*)::bigint                                                   AS matches,
       count(*) FILTER (WHERE has_stats)::bigint                          AS with_stats,
       coalesce(sum(serve_points) FILTER (WHERE has_stats), 0)::bigint    AS serve_points,
       coalesce(sum(first_won + second_won) FILTER (WHERE has_stats), 0)::bigint AS serve_won,
       coalesce(sum(op_serve_points) FILTER (WHERE has_stats), 0)::bigint AS return_points,
       coalesce(sum(op_serve_points - op_first_won - op_second_won)
                FILTER (WHERE has_stats), 0)::bigint                      AS return_won,
       coalesce(sum(bp_saved) FILTER (WHERE has_stats), 0)::bigint        AS bp_saved,
       coalesce(sum(bp_faced) FILTER (WHERE has_stats), 0)::bigint        AS bp_faced,
       coalesce(sum(op_bp_faced - op_bp_saved) FILTER (WHERE has_stats), 0)::bigint AS bp_won,
       coalesce(sum(op_bp_faced) FILTER (WHERE has_stats), 0)::bigint     AS bp_chances,
       coalesce(sum(tiebreaks_won), 0)::bigint                            AS tiebreaks_won,
       coalesce(sum(tiebreaks_played), 0)::bigint                         AS tiebreaks_played,
       count(*) FILTER (WHERE deciding_set AND won)::bigint               AS deciders_won,
       count(*) FILTER (WHERE deciding_set)::bigint                       AS deciders_played,
       count(*) FILTER (WHERE level = 'G' OR opponent_rank <= 10)::bigint AS big_played,
       count(*) FILTER (WHERE (level = 'G' OR opponent_rank <= 10) AND won)::bigint AS big_won
  FROM lines
 GROUP BY player_id
`

type ListTourWindowTotalsParams struct {
	Tour     Tour
	FromDate time.Time
	ToDate   time.Time
}

type ListTourWindowTotalsRow struct {
	PlayerID        int64
	Matches         int64
	WithStats       int64
	ServePoints     int64
	ServeWon        int64
	ReturnPoints    int64
	ReturnWon       int64
	BpSaved         int64
	BpFaced         int64
	BpWon           int64
	BpChances       int64
	TiebreaksWon    int64
	TiebreaksPlayed int64
	DecidersWon     int64
	DecidersPlayed  int64
	BigPlayed       int64
	BigWon          int64
}

// Every tour-level player's totals over one window: the population a
// percentile is read against. Serve and return counts only where both lines
// were recorded, so the two share a denominator.
func (q *Queries) ListTourWindowTotals(ctx context.Context, arg ListTourWindowTotalsParams) ([]ListTourWindowTotalsRow, error) {
	rows, err := q.db.Query(ctx, listTourWindowTotals, arg.Tour, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTourWindowTotalsRow{}
	for rows.Next() {
		var i ListTourWindowTotalsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Matches,
			&i.WithStats,
			&i.ServePoints,
			&i.ServeWon,
			&i.ReturnPoints,
			&i.ReturnWon,
			&i.BpSaved,
			&i.BpFaced,
			&i.BpWon,
			&i.BpChances,
			&i.TiebreaksWon,
			&i.TiebreaksPlayed,
			&i.DecidersWon,
			&i.DecidersPlayed,
			&i.BigPlayed,
			&i.BigWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayers = `-- name: SearchPlayers :many
WITH scored AS (
    SELECT p.id, p.slug, p.tour, p.full_name, p.country,
           similarity(p.full_name, $4::text)::real AS score,
           p.career_matches::bigint                   AS matches,
           coalesce(p.best_tier::text, '')            AS best_tier
      FROM players p
     WHERE p.full_name % $4::text
       AND ($5::tour IS NULL OR p.tour = $5::tour)
),
ranked AS (
    SELECT s.id, s.slug, s.tour, s.full_name, s.country, s.score, s.matches, s.best_tier,
           (s.score * CASE s.best_tier
               WHEN 'tour'       THEN 1.00
               WHEN 'challenger' THEN 0.85
               WHEN 'futures'    THEN 0.70
               WHEN 'itf'        THEN 0.70
               ELSE 0.60
            END)::real AS rank
      FROM scored s
)
SELECT id, slug, tour, full_name, country, score, matches, best_tier::text AS best_tier, rank
  FROM ranked
 -- Rank descends but id ascends, so the row-value form (rank, id) < (...)
 -- would walk the wrong way through a run of equal ranks and repeat rows.
 WHERE ($1::real IS NULL
        OR rank < $1::real
        OR (rank = $1::real AND id > $2::bigint))
 ORDER BY rank DESC, id
 LIMIT $3
`

type SearchPlayersParams struct {
	AfterRank *float32
	AfterID   *int64
	RowLimit  int32
	Query     string
	Tour      *Tour
}

type SearchPlayersRow struct {
	ID       int64
	Slug     string
	Tour     Tour
	FullName string
	Country  *string
	Score    float32
	Matches  int64
	BestTier string
	Rank     float32
}

// Trigram search over 115k players. Similarity alone makes "Alexander" useless,
// so the score is weighted by the best tier the player has reached: the weights
// only ever reorder names of comparable similarity. Ordering on the single
// combined rank keeps the keyset cursor to one value plus the id tiebreak.
func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers,
		arg.AfterRank,
		arg.AfterID,
		arg.RowLimit,
		arg.Query,
		arg.Tour,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Tour,
			&i.FullName,
			&i.Country,
			&i.Score,
			&i.Matches,
			&i.BestTier,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
