// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"time"
)

const getPlayerBySlug = `-- name: GetPlayerBySlug :one
SELECT id, slug, tour, full_name, first_name, last_name, country, hand,
       height_cm, birth_date, pro_since, wikidata_id
  FROM players
 WHERE slug = $1
`

type GetPlayerBySlugRow struct {
	ID         int64
	Slug       string
	Tour       Tour
	FullName   string
	FirstName  *string
	LastName   *string
	Country    *string
	Hand       *Hand
	HeightCm   *int16
	BirthDate  *time.Time
	ProSince   *int16
	WikidataID *string
}

func (q *Queries) GetPlayerBySlug(ctx context.Context, slug string) (GetPlayerBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPlayerBySlug, slug)
	var i GetPlayerBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Tour,
		&i.FullName,
		&i.FirstName,
		&i.LastName,
		&i.Country,
		&i.Hand,
		&i.HeightCm,
		&i.BirthDate,
		&i.ProSince,
		&i.WikidataID,
	)
	return i, err
}

const getPlayerCareerSummary = `-- name: GetPlayerCareerSummary :one
WITH played AS (
    SELECT mp.won, mp.aces, mp.double_faults, mp.serve_points, mp.first_in,
           mp.first_won, mp.second_won, mp.serve_games, mp.bp_saved, mp.bp_faced,
           m.incomplete, m.round, m.is_qualifying, m.played_on
      FROM match_players mp
      JOIN matches m ON m.id = mp.match_id
     WHERE mp.player_id = $1
),
counted AS (
    SELECT count(*)::bigint                             AS matches,
           count(*) FILTER (WHERE won)::bigint          AS wins,
           count(*) FILTER (WHERE NOT won)::bigint      AS losses,
           -- Retirements and walkovers count here but are excluded from rates.
           count(*) FILTER (WHERE incomplete)::bigint   AS incomplete_matches,
           count(*) FILTER (WHERE won AND round = 'F' AND NOT is_qualifying)::bigint AS titles,
           min(played_on)::date                         AS first_match,
           max(played_on)::date                         AS last_match
      FROM played
    -- No matches means no career summary at all. Returning a row of
    -- NULLs instead would not survive the scan.
    HAVING count(*) > 0
),
served AS (
    SELECT count(*)::bigint         AS stat_matches,
           coalesce(sum(aces), 0)::bigint        AS aces,
           coalesce(sum(double_faults), 0)::bigint AS double_faults,
           coalesce(sum(serve_points), 0)::bigint  AS serve_points,
           coalesce(sum(first_in), 0)::bigint      AS first_in,
           coalesce(sum(first_won), 0)::bigint     AS first_won,
           coalesce(sum(second_won), 0)::bigint    AS second_won,
           coalesce(sum(serve_games), 0)::bigint   AS serve_games,
           coalesce(sum(bp_saved), 0)::bigint      AS bp_saved,
           coalesce(sum(bp_faced), 0)::bigint      AS bp_faced
      FROM played
     WHERE serve_points IS NOT NULL AND NOT incomplete
)
SELECT matches, wins, losses, incomplete_matches, titles, first_match, last_match, stat_matches, aces, double_faults, serve_points, first_in, first_won, second_won, serve_games, bp_saved, bp_faced FROM counted, served
`

type GetPlayerCareerSummaryRow struct {
	Matches           int64
	Wins              int64
	Losses            int64
	IncompleteMatches int64
	Titles            int64
	FirstMatch        time.Time
	LastMatch         time.Time
	StatMatches       int64
	Aces              int64
	DoubleFaults      int64
	ServePoints       int64
	FirstIn           int64
	FirstWon          int64
	SecondWon         int64
	ServeGames        int64
	BpSaved           int64
	BpFaced           int64
}

// Rate statistics come from a separate aggregate over only the matches that
// recorded them: a NULL sum with stat_matches = 0 means never recorded, which
// the response must not collapse into a zero.
func (q *Queries) GetPlayerCareerSummary(ctx context.Context, playerID int64) (GetPlayerCareerSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPlayerCareerSummary, playerID)
	var i GetPlayerCareerSummaryRow
	err := row.Scan(
		&i.Matches,
		&i.Wins,
		&i.Losses,
		&i.IncompleteMatches,
		&i.Titles,
		&i.FirstMatch,
		&i.LastMatch,
		&i.StatMatches,
		&i.Aces,
		&i.DoubleFaults,
		&i.ServePoints,
		&i.FirstIn,
		&i.FirstWon,
		&i.SecondWon,
		&i.ServeGames,
		&i.BpSaved,
		&i.BpFaced,
	)
	return i, err
}

const getPlayerSurfaceSplits = `-- name: GetPlayerSurfaceSplits :many
SELECT m.surface,
       count(*)::bigint                            AS matches,
       count(*) FILTER (WHERE mp.won)::bigint      AS wins,
       count(*) FILTER (WHERE NOT mp.won)::bigint  AS losses
  FROM match_players mp
  JOIN matches m ON m.id = mp.match_id
 WHERE mp.player_id = $1
 GROUP BY m.surface
 ORDER BY matches DESC
`

type GetPlayerSurfaceSplitsRow struct {
	Surface *Surface
	Matches int64
	Wins    int64
	Losses  int64
}

func (q *Queries) GetPlayerSurfaceSplits(ctx context.Context, playerID int64) ([]GetPlayerSurfaceSplitsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerSurfaceSplits, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerSurfaceSplitsRow{}
	for rows.Next() {
		var i GetPlayerSurfaceSplitsRow
		if err := rows.Scan(
			&i.Surface,
			&i.Matches,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTierSplits = `-- name: GetPlayerTierSplits :many
SELECT t.tier,
       count(*)::bigint                                       AS matches,
       count(*) FILTER (WHERE m.has_detailed_stats)::bigint   AS matches_with_stats
  FROM match_players mp
  JOIN matches m     ON m.id = mp.match_id
  JOIN tournaments t ON t.id = m.tournament_id
 WHERE mp.player_id = $1
 GROUP BY t.tier
 ORDER BY matches DESC
`

type GetPlayerTierSplitsRow struct {
	Tier             Tier
	Matches          int64
	MatchesWithStats int64
}

// Which tiers a player competed at, so the API can say a statistic was never
// recorded for their level rather than implying it was zero.
func (q *Queries) GetPlayerTierSplits(ctx context.Context, playerID int64) ([]GetPlayerTierSplitsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerTierSplits, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerTierSplitsRow{}
	for rows.Next() {
		var i GetPlayerTierSplitsRow
		if err := rows.Scan(&i.Tier, &i.Matches, &i.MatchesWithStats); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayers = `-- name: SearchPlayers :many
WITH scored AS (
    SELECT p.id, p.slug, p.tour, p.full_name, p.country,
           similarity(p.full_name, $4::text)::real AS score,
           p.career_matches::bigint                   AS matches,
           coalesce(p.best_tier::text, '')            AS best_tier
      FROM players p
     WHERE p.full_name % $4::text
       AND ($5::tour IS NULL OR p.tour = $5::tour)
),
ranked AS (
    SELECT s.id, s.slug, s.tour, s.full_name, s.country, s.score, s.matches, s.best_tier,
           (s.score * CASE s.best_tier
               WHEN 'tour'       THEN 1.00
               WHEN 'challenger' THEN 0.85
               WHEN 'futures'    THEN 0.70
               WHEN 'itf'        THEN 0.70
               ELSE 0.60
            END)::real AS rank
      FROM scored s
)
SELECT id, slug, tour, full_name, country, score, matches, best_tier::text AS best_tier, rank
  FROM ranked
 -- Rank descends but id ascends, so the row-value form (rank, id) < (...)
 -- would walk the wrong way through a run of equal ranks and repeat rows.
 WHERE ($1::real IS NULL
        OR rank < $1::real
        OR (rank = $1::real AND id > $2::bigint))
 ORDER BY rank DESC, id
 LIMIT $3
`

type SearchPlayersParams struct {
	AfterRank *float32
	AfterID   *int64
	RowLimit  int32
	Query     string
	Tour      *Tour
}

type SearchPlayersRow struct {
	ID       int64
	Slug     string
	Tour     Tour
	FullName string
	Country  *string
	Score    float32
	Matches  int64
	BestTier string
	Rank     float32
}

// Trigram search over 115k players. Similarity alone makes "Alexander" useless,
// so the score is weighted by the best tier the player has reached: the weights
// only ever reorder names of comparable similarity. Ordering on the single
// combined rank keeps the keyset cursor to one value plus the id tiebreak.
func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers,
		arg.AfterRank,
		arg.AfterID,
		arg.RowLimit,
		arg.Query,
		arg.Tour,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Tour,
			&i.FullName,
			&i.Country,
			&i.Score,
			&i.Matches,
			&i.BestTier,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
