// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rankings.sql

package db

import (
	"context"
	"time"
)

const bestSurfaceEloAsOf = `-- name: BestSurfaceEloAsOf :many
WITH latest AS (
    SELECT DISTINCT ON (r.player_id, r.surface)
           r.player_id, r.surface, r.elo, r.matches_played
      FROM ratings r
     WHERE r.surface <> 'overall'
       AND r.as_of <= $1::date
       AND r.as_of > $2::date
       AND r.player_id = ANY($3::bigint[])
     ORDER BY r.player_id, r.surface, r.as_of DESC
)
SELECT DISTINCT ON (l.player_id) l.player_id, l.surface, l.elo::float8 AS elo, l.matches_played
  FROM latest l
 ORDER BY l.player_id, l.elo DESC, l.surface
`

type BestSurfaceEloAsOfParams struct {
	OnDate    time.Time
	Since     time.Time
	PlayerIds []int64
}

type BestSurfaceEloAsOfRow struct {
	PlayerID      int64
	Surface       RatingSurface
	Elo           float64
	MatchesPlayed int32
}

// The surface each of a page of players is currently best on, and the rating
// there, as of a date. The same window the leaderboard uses, so a surface
// last played years ago is not anyone's best today, and the raw series rather
// than the blend: it is the figure the player page's strip shows.
func (q *Queries) BestSurfaceEloAsOf(ctx context.Context, arg BestSurfaceEloAsOfParams) ([]BestSurfaceEloAsOfRow, error) {
	rows, err := q.db.Query(ctx, bestSurfaceEloAsOf, arg.OnDate, arg.Since, arg.PlayerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BestSurfaceEloAsOfRow{}
	for rows.Next() {
		var i BestSurfaceEloAsOfRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Surface,
			&i.Elo,
			&i.MatchesPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const currentEloAsOf = `-- name: CurrentEloAsOf :many
SELECT DISTINCT ON (r.player_id) r.player_id, r.elo::float8 AS elo, r.matches_played
  FROM ratings r
 WHERE r.surface = $1::rating_surface
   AND r.as_of <= $2::date
   AND r.player_id = ANY($3::bigint[])
 ORDER BY r.player_id, r.as_of DESC
`

type CurrentEloAsOfParams struct {
	Surface   RatingSurface
	OnDate    time.Time
	PlayerIds []int64
}

type CurrentEloAsOfRow struct {
	PlayerID      int64
	Elo           float64
	MatchesPlayed int32
}

// The rating each of a page of players held at a date. Sparse table, so it is
// their last row at or before it.
//
// matches_played comes along because the simulator blends a surface rating with
// the overall one by how much of that surface a player has actually played, and
// a blend without the weight is an average of two numbers that mean different
// things.
func (q *Queries) CurrentEloAsOf(ctx context.Context, arg CurrentEloAsOfParams) ([]CurrentEloAsOfRow, error) {
	rows, err := q.db.Query(ctx, currentEloAsOf, arg.Surface, arg.OnDate, arg.PlayerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentEloAsOfRow{}
	for rows.Next() {
		var i CurrentEloAsOfRow
		if err := rows.Scan(&i.PlayerID, &i.Elo, &i.MatchesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const effectiveEloDate = `-- name: EffectiveEloDate :one
SELECT r.as_of
  FROM ratings r
  JOIN players p ON p.id = r.player_id
 WHERE r.surface = $1::rating_surface
   AND r.as_of <= $2::date
   AND ($3::tour IS NULL OR p.tour = $3::tour)
 ORDER BY r.as_of DESC
 LIMIT 1
`

type EffectiveEloDateParams struct {
	Surface    RatingSurface
	OnOrBefore time.Time
	Tour       *Tour
}

// The most recent week the ratings actually have, at or before the one asked
// for. Never today: the coverage gap means those differ, and answering a
// request for the current rankings with an empty list because today is outside
// coverage is exactly the failure ADR-0006 exists to avoid.
//
// The bound is not nullable: a caller who named no date passes the end of time,
// which reads better than a nullable parameter and is the same question.
//
// ORDER BY and LIMIT rather than max(): an aggregate always returns a row, and
// that row is NULL when nothing matched, which is a scan error rather than the
// no-rows the caller can act on.
//
// The tour filter belongs here and not only on the leaderboard. WTA data stops
// four years before ATP data does, and resolving the date across both tours
// answers a request for the WTA rankings with an ATP week and an empty list.
func (q *Queries) EffectiveEloDate(ctx context.Context, arg EffectiveEloDateParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, effectiveEloDate, arg.Surface, arg.OnOrBefore, arg.Tour)
	var as_of time.Time
	err := row.Scan(&as_of)
	return as_of, err
}

const effectiveOfficialDate = `-- name: EffectiveOfficialDate :one
SELECT r.ranking_date
  FROM rankings r
  JOIN players p ON p.id = r.player_id
 WHERE ($1::tour IS NULL OR p.tour = $1::tour)
   AND r.ranking_date <= $2::date
 ORDER BY r.ranking_date DESC
 LIMIT 1
`

type EffectiveOfficialDateParams struct {
	Tour       *Tour
	OnOrBefore time.Time
}

func (q *Queries) EffectiveOfficialDate(ctx context.Context, arg EffectiveOfficialDateParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, effectiveOfficialDate, arg.Tour, arg.OnOrBefore)
	var ranking_date time.Time
	err := row.Scan(&ranking_date)
	return ranking_date, err
}

const listEloRankings = `-- name: ListEloRankings :many
WITH recent AS (
    SELECT DISTINCT ON (r.player_id)
           r.player_id, r.elo, r.as_of, r.matches_played
      FROM ratings r
     WHERE r.surface = $5::rating_surface
       AND r.as_of <= $6::date
       AND r.as_of > $7::date
     ORDER BY r.player_id, r.as_of DESC
),
ranked AS (
    SELECT c.player_id, c.elo::float8 AS elo, c.matches_played,
           p.slug, p.full_name, p.tour, p.country, p.birth_date,
           rank() OVER (ORDER BY c.elo DESC, c.player_id)::int AS position
      FROM recent c
      JOIN players p ON p.id = c.player_id
     WHERE ($8::tour IS NULL OR p.tour = $8::tour)
)
SELECT k.player_id, k.slug, k.full_name, k.tour, k.country, k.birth_date,
       k.elo, k.matches_played, k.position,
       o.rank AS official_rank, o.points
  FROM ranked k
  LEFT JOIN rankings o
         ON o.player_id = k.player_id AND o.ranking_date = $1::date
 WHERE ($2::float8 IS NULL
        OR k.elo < $2::float8
        OR (k.elo = $2::float8
            AND k.player_id > $3::bigint))
 ORDER BY k.elo DESC, k.player_id
 LIMIT $4
`

type ListEloRankingsParams struct {
	OfficialDate time.Time
	AfterElo     *float64
	AfterID      *int64
	RowLimit     int32
	Surface      RatingSurface
	OnDate       time.Time
	Since        time.Time
	Tour         *Tour
}

type ListEloRankingsRow struct {
	PlayerID      int64
	Slug          string
	FullName      string
	Tour          Tour
	Country       *string
	BirthDate     *time.Time
	Elo           float64
	MatchesPlayed int32
	Position      int32
	OfficialRank  *int32
	Points        *int32
}

func (q *Queries) ListEloRankings(ctx context.Context, arg ListEloRankingsParams) ([]ListEloRankingsRow, error) {
	rows, err := q.db.Query(ctx, listEloRankings,
		arg.OfficialDate,
		arg.AfterElo,
		arg.AfterID,
		arg.RowLimit,
		arg.Surface,
		arg.OnDate,
		arg.Since,
		arg.Tour,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEloRankingsRow{}
	for rows.Next() {
		var i ListEloRankingsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Slug,
			&i.FullName,
			&i.Tour,
			&i.Country,
			&i.BirthDate,
			&i.Elo,
			&i.MatchesPlayed,
			&i.Position,
			&i.OfficialRank,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialRankings = `-- name: ListOfficialRankings :many
SELECT o.player_id, p.slug, p.full_name, p.tour, p.country, p.birth_date,
       o.rank, o.points
  FROM rankings o
  JOIN players p ON p.id = o.player_id
 WHERE o.ranking_date = $1::date
   AND ($2::tour IS NULL OR p.tour = $2::tour)
   AND ($3::int IS NULL
        OR o.rank > $3::int
        OR (o.rank = $3::int
            AND o.player_id > $4::bigint))
 ORDER BY o.rank, o.player_id
 LIMIT $5
`

type ListOfficialRankingsParams struct {
	OnDate    time.Time
	Tour      *Tour
	AfterRank *int32
	AfterID   *int64
	RowLimit  int32
}

type ListOfficialRankingsRow struct {
	PlayerID  int64
	Slug      string
	FullName  string
	Tour      Tour
	Country   *string
	BirthDate *time.Time
	Rank      int32
	Points    *int32
}

// The tour's own list for one week. Elo comes from CurrentEloAsOf for the page
// rather than a correlated subquery here: a player the ratings have never seen
// has no Elo, and sqlc reads a subquery in the select list as never null.
func (q *Queries) ListOfficialRankings(ctx context.Context, arg ListOfficialRankingsParams) ([]ListOfficialRankingsRow, error) {
	rows, err := q.db.Query(ctx, listOfficialRankings,
		arg.OnDate,
		arg.Tour,
		arg.AfterRank,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialRankingsRow{}
	for rows.Next() {
		var i ListOfficialRankingsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Slug,
			&i.FullName,
			&i.Tour,
			&i.Country,
			&i.BirthDate,
			&i.Rank,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingTrajectories = `-- name: ListRatingTrajectories :many
SELECT r.player_id, r.as_of AS week, r.elo::float8 AS elo
  FROM ratings r
 WHERE r.surface = $1::rating_surface
   AND r.player_id = ANY($2::bigint[])
   AND r.as_of > $3::date
   AND r.as_of <= $4::date
 ORDER BY r.player_id, r.as_of
`

type ListRatingTrajectoriesParams struct {
	Surface   RatingSurface
	PlayerIds []int64
	FromDate  time.Time
	ToDate    time.Time
}

type ListRatingTrajectoriesRow struct {
	PlayerID int64
	Week     time.Time
	Elo      float64
}

// The weekly series for a handful of players, which is what a multi-series
// chart is: one line each, rather than a leaderboard.
//
// The bounds are two plain dates rather than a date and a width. The caller has
// to know the window anyway to label the chart, and sqlc miscompiles the
// arithmetic form here.
func (q *Queries) ListRatingTrajectories(ctx context.Context, arg ListRatingTrajectoriesParams) ([]ListRatingTrajectoriesRow, error) {
	rows, err := q.db.Query(ctx, listRatingTrajectories,
		arg.Surface,
		arg.PlayerIds,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingTrajectoriesRow{}
	for rows.Next() {
		var i ListRatingTrajectoriesRow
		if err := rows.Scan(&i.PlayerID, &i.Week, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peakEloAsOf = `-- name: PeakEloAsOf :many
SELECT player_id, max(elo)::float8 AS peak
  FROM ratings
 WHERE surface = $1::rating_surface
   AND as_of <= $2::date
   AND player_id = ANY($3::bigint[])
 GROUP BY player_id
`

type PeakEloAsOfParams struct {
	Surface   RatingSurface
	OnDate    time.Time
	PlayerIds []int64
}

type PeakEloAsOfRow struct {
	PlayerID int64
	Peak     float64
}

func (q *Queries) PeakEloAsOf(ctx context.Context, arg PeakEloAsOfParams) ([]PeakEloAsOfRow, error) {
	rows, err := q.db.Query(ctx, peakEloAsOf, arg.Surface, arg.OnDate, arg.PlayerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeakEloAsOfRow{}
	for rows.Next() {
		var i PeakEloAsOfRow
		if err := rows.Scan(&i.PlayerID, &i.Peak); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
