// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seasons.sql

package db

import (
	"context"
	"time"
)

const listSeasonEvents = `-- name: ListSeasonEvents :many
SELECT t.id, t.tour::text AS tour, e.slug AS event_slug, e.name AS event_name,
       t.name, t.level, t.tier::text AS tier, coalesce(t.surface::text, '')::text AS surface,
       t.draw_size, t.start_date, t.event_link,
       CASE
           WHEN t.level = 'D' OR t.event_link = 'team' THEN 'team'
           WHEN t.level = 'G' THEN 'slam'
           WHEN t.level IN ('M', 'PM', '1000') THEN 'masters'
           WHEN t.level = 'F' THEN 'finals'
           WHEN t.level = 'O' THEN 'olympics'
           ELSE t.tier::text
       END AS category,
       f.score AS final_score,
       w.slug AS champion_slug, w.full_name AS champion_name,
       l.slug AS finalist_slug, l.full_name AS finalist_name,
       (SELECT count(*)::int FROM matches m WHERE m.tournament_id = t.id) AS matches
  FROM tournaments t
  LEFT JOIN events e ON e.id = t.event_id
  LEFT JOIN LATERAL (
        SELECT m.score, m.winner_id, m.loser_id
          FROM matches m
         WHERE m.tournament_id = t.id AND m.round = 'F'
           AND NOT m.is_qualifying AND NOT m.is_team_event
         ORDER BY m.match_num DESC
         LIMIT 1) f ON true
  LEFT JOIN players w ON w.id = f.winner_id
  LEFT JOIN players l ON l.id = f.loser_id
 WHERE t.season = $1::smallint
   AND ($2::tour IS NULL OR t.tour = $2::tour)
   AND t.tier = $3::tier
 ORDER BY t.tour, t.start_date, t.id
`

type ListSeasonEventsParams struct {
	Season int16
	Tour   *Tour
	Tier   Tier
}

type ListSeasonEventsRow struct {
	ID           int64
	Tour         string
	EventSlug    *string
	EventName    *string
	Name         string
	Level        string
	Tier         string
	Surface      string
	DrawSize     *int16
	StartDate    time.Time
	EventLink    *string
	Category     string
	FinalScore   *string
	ChampionSlug *string
	ChampionName *string
	FinalistSlug *string
	FinalistName *string
	Matches      int32
}

// Every tournament of one season at one tier, either tour or both, in
// calendar order, with its final and the event it belongs to. The category
// is the index's, so the year page groups by the same words.
func (q *Queries) ListSeasonEvents(ctx context.Context, arg ListSeasonEventsParams) ([]ListSeasonEventsRow, error) {
	rows, err := q.db.Query(ctx, listSeasonEvents, arg.Season, arg.Tour, arg.Tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonEventsRow{}
	for rows.Next() {
		var i ListSeasonEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Tour,
			&i.EventSlug,
			&i.EventName,
			&i.Name,
			&i.Level,
			&i.Tier,
			&i.Surface,
			&i.DrawSize,
			&i.StartDate,
			&i.EventLink,
			&i.Category,
			&i.FinalScore,
			&i.ChampionSlug,
			&i.ChampionName,
			&i.FinalistSlug,
			&i.FinalistName,
			&i.Matches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonSummaries = `-- name: ListSeasonSummaries :many
SELECT t.season, t.tour::text AS tour,
       count(*) FILTER (WHERE coalesce(t.event_link, '') <> 'team')::int AS events,
       count(*) FILTER (WHERE t.event_link = 'team')::int AS ties,
       count(*) FILTER (WHERE t.surface = 'hard'   AND coalesce(t.event_link, '') <> 'team')::int AS hard,
       count(*) FILTER (WHERE t.surface = 'clay'   AND coalesce(t.event_link, '') <> 'team')::int AS clay,
       count(*) FILTER (WHERE t.surface = 'grass'  AND coalesce(t.event_link, '') <> 'team')::int AS grass,
       count(*) FILTER (WHERE t.surface = 'carpet' AND coalesce(t.event_link, '') <> 'team')::int AS carpet,
       count(*) FILTER (WHERE t.surface IS NULL    AND coalesce(t.event_link, '') <> 'team')::int AS unknown
  FROM tournaments t
 GROUP BY t.season, t.tour
 ORDER BY t.season DESC, t.tour
`

type ListSeasonSummariesRow struct {
	Season  int16
	Tour    string
	Events  int32
	Ties    int32
	Hard    int32
	Clay    int32
	Grass   int32
	Carpet  int32
	Unknown int32
}

// One row per season and tour: how many events were played and on what, with
// a team competition's ties counted apart, since a tie is not an event on a
// calendar. Every season in the table, so the women's tour's years before
// 1968 are rows with no men's half rather than years the page starts after.
func (q *Queries) ListSeasonSummaries(ctx context.Context) ([]ListSeasonSummariesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonSummariesRow{}
	for rows.Next() {
		var i ListSeasonSummariesRow
		if err := rows.Scan(
			&i.Season,
			&i.Tour,
			&i.Events,
			&i.Ties,
			&i.Hard,
			&i.Clay,
			&i.Grass,
			&i.Carpet,
			&i.Unknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlamFinals = `-- name: ListSlamFinals :many
SELECT t.season, t.tour::text AS tour, e.slug, e.name, t.start_date,
       f.score AS final_score,
       w.slug AS champion_slug, w.full_name AS champion_name,
       l.slug AS finalist_slug, l.full_name AS finalist_name
  FROM tournaments t
  JOIN events e ON e.id = t.event_id
  LEFT JOIN LATERAL (
        SELECT m.score, m.winner_id, m.loser_id
          FROM matches m
         WHERE m.tournament_id = t.id AND m.round = 'F'
           AND NOT m.is_qualifying AND NOT m.is_team_event
         ORDER BY m.match_num DESC
         LIMIT 1) f ON true
  LEFT JOIN players w ON w.id = f.winner_id
  LEFT JOIN players l ON l.id = f.loser_id
 WHERE t.level = 'G'
   AND EXISTS (SELECT 1 FROM matches m WHERE m.tournament_id = t.id AND NOT m.is_qualifying)
 ORDER BY t.season DESC, t.tour, t.start_date, t.id
`

type ListSlamFinalsRow struct {
	Season       int16
	Tour         string
	Slug         string
	Name         string
	StartDate    time.Time
	FinalScore   *string
	ChampionSlug *string
	ChampionName *string
	FinalistSlug *string
	FinalistName *string
}

// Every Grand Slam edition with its final, in calendar order within a
// season: the four names a season row carries. The finals index makes each
// one a lookup rather than a pass over the draw. A row filed at Slam level
// that holds only qualifying (the 2021 Australian Open's qualifying, played
// in Doha and Dubai) is not an edition and is left out.
func (q *Queries) ListSlamFinals(ctx context.Context) ([]ListSlamFinalsRow, error) {
	rows, err := q.db.Query(ctx, listSlamFinals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlamFinalsRow{}
	for rows.Next() {
		var i ListSlamFinalsRow
		if err := rows.Scan(
			&i.Season,
			&i.Tour,
			&i.Slug,
			&i.Name,
			&i.StartDate,
			&i.FinalScore,
			&i.ChampionSlug,
			&i.ChampionName,
			&i.FinalistSlug,
			&i.FinalistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
