// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulate.sql

package db

import (
	"context"
	"time"
)

const findTournament = `-- name: FindTournament :one
SELECT id, name, season, tour::text AS tour, tier::text AS tier,
       -- The source leaves surface blank for some events. "unknown" is the same
       -- stand-in the career and head-to-head splits use, so one absent surface
       -- does not have two spellings across the API.
       coalesce(surface::text, 'unknown') AS surface,
       level, draw_size, start_date
  FROM tournaments
 WHERE tour = $1::tour AND season = $2::smallint AND lower(name) = lower($3::text)
 ORDER BY start_date
 LIMIT 1
`

type FindTournamentParams struct {
	Tour   Tour
	Season int16
	Name   string
}

type FindTournamentRow struct {
	ID        int64
	Name      string
	Season    int16
	Tour      string
	Tier      string
	Surface   interface{}
	Level     string
	DrawSize  *int16
	StartDate time.Time
}

// Resolve an event by what a URL can carry, rather than by a numeric id nobody
// can read or guess.
func (q *Queries) FindTournament(ctx context.Context, arg FindTournamentParams) (FindTournamentRow, error) {
	row := q.db.QueryRow(ctx, findTournament, arg.Tour, arg.Season, arg.Name)
	var i FindTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.Tour,
		&i.Tier,
		&i.Surface,
		&i.Level,
		&i.DrawSize,
		&i.StartDate,
	)
	return i, err
}

const listDrawMatches = `-- name: ListDrawMatches :many
SELECT m.round,
       m.winner_id, wp.slug AS winner_slug, wp.full_name AS winner_name, wmp.seed AS winner_seed,
       m.loser_id,  lp.slug AS loser_slug,  lp.full_name AS loser_name,  lmp.seed AS loser_seed
  FROM matches m
  JOIN players wp ON wp.id = m.winner_id
  JOIN players lp ON lp.id = m.loser_id
  LEFT JOIN match_players wmp ON wmp.match_id = m.id AND wmp.player_id = m.winner_id
  LEFT JOIN match_players lmp ON lmp.match_id = m.id AND lmp.player_id = m.loser_id
 WHERE m.tournament_id = $1
   AND NOT m.is_qualifying
   AND NOT m.is_team_event
 ORDER BY m.match_num
`

type ListDrawMatchesRow struct {
	Round      string
	WinnerID   int64
	WinnerSlug string
	WinnerName string
	WinnerSeed *int16
	LoserID    int64
	LoserSlug  string
	LoserName  string
	LoserSeed  *int16
}

// Every main-draw match of one event, with both players, for reconstructing the
// bracket.
//
// Qualifying is a separate draw and team events are not a draw at all -- 341 ATP
// "tour" events with a stated draw size of 4 are Davis Cup ties, and every one
// of their matches carries the team flag.
func (q *Queries) ListDrawMatches(ctx context.Context, tournamentID int64) ([]ListDrawMatchesRow, error) {
	rows, err := q.db.Query(ctx, listDrawMatches, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrawMatchesRow{}
	for rows.Next() {
		var i ListDrawMatchesRow
		if err := rows.Scan(
			&i.Round,
			&i.WinnerID,
			&i.WinnerSlug,
			&i.WinnerName,
			&i.WinnerSeed,
			&i.LoserID,
			&i.LoserSlug,
			&i.LoserName,
			&i.LoserSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulatableEvents = `-- name: ListSimulatableEvents :many
SELECT t.id, t.name, t.season, t.tour::text AS tour, t.tier::text AS tier,
       coalesce(t.surface::text, 'unknown') AS surface,
       t.start_date, count(*)::bigint AS matches
  FROM tournaments t
  JOIN matches m ON m.tournament_id = t.id
 WHERE NOT m.is_qualifying AND NOT m.is_team_event
   AND ($1::tour IS NULL OR t.tour = $1::tour)
   AND ($2::smallint IS NULL OR t.season = $2::smallint)
 GROUP BY t.id
HAVING count(*) IN (7, 15, 31, 63, 127)
 ORDER BY t.season DESC, count(*) DESC, t.name
 LIMIT $3
`

type ListSimulatableEventsParams struct {
	Tour     *Tour
	Season   *int16
	RowLimit int32
}

type ListSimulatableEventsRow struct {
	ID        int64
	Name      string
	Season    int16
	Tour      string
	Tier      string
	Surface   interface{}
	StartDate time.Time
	Matches   int64
}

// Events whose main draw is a complete power-of-two bracket, which is the only
// shape that reconstructs. Byes and round-robin groups leave a round with the
// wrong number of matches and are excluded here rather than failing one at a
// time in the reconstruction.
func (q *Queries) ListSimulatableEvents(ctx context.Context, arg ListSimulatableEventsParams) ([]ListSimulatableEventsRow, error) {
	rows, err := q.db.Query(ctx, listSimulatableEvents, arg.Tour, arg.Season, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSimulatableEventsRow{}
	for rows.Next() {
		var i ListSimulatableEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Season,
			&i.Tour,
			&i.Tier,
			&i.Surface,
			&i.StartDate,
			&i.Matches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
