// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulate.sql

package db

import (
	"context"
	"time"
)

const findTournament = `-- name: FindTournament :one
SELECT id, name, season, tour::text AS tour, tier::text AS tier,
       -- The source leaves surface blank for some events. "unknown" is the same
       -- stand-in the career and head-to-head splits use, so one absent surface
       -- does not have two spellings across the API.
       coalesce(surface::text, 'unknown')::text AS surface,
       level, draw_size, start_date
  FROM tournaments
 WHERE tour = $1::tour AND season = $2::smallint AND lower(name) = lower($3::text)
 ORDER BY start_date
 LIMIT 1
`

type FindTournamentParams struct {
	Tour   Tour
	Season int16
	Name   string
}

type FindTournamentRow struct {
	ID        int64
	Name      string
	Season    int16
	Tour      string
	Tier      string
	Surface   string
	Level     string
	DrawSize  *int16
	StartDate time.Time
}

// Resolve an event by what a URL can carry, rather than by a numeric id nobody
// can read or guess.
func (q *Queries) FindTournament(ctx context.Context, arg FindTournamentParams) (FindTournamentRow, error) {
	row := q.db.QueryRow(ctx, findTournament, arg.Tour, arg.Season, arg.Name)
	var i FindTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.Tour,
		&i.Tier,
		&i.Surface,
		&i.Level,
		&i.DrawSize,
		&i.StartDate,
	)
	return i, err
}

const getSimulationPlayer = `-- name: GetSimulationPlayer :one
SELECT p.id, p.slug, p.full_name, p.tour::text AS tour, p.country,
       coalesce(p.best_tier::text, 'tour')::text AS best_tier,
       -- The season decides which decade of the serve baseline anchors the
       -- inversion. Zero is not a season, so it is an unambiguous stand-in for
       -- a player with no matches at all -- who has no rating either, and is
       -- therefore not simulatable for a different reason.
       coalesce((SELECT max(t.season)
                   FROM match_players mp
                   JOIN matches m     ON m.id = mp.match_id
                   JOIN tournaments t ON t.id = m.tournament_id
                  WHERE mp.player_id = p.id), 0)::smallint AS last_season
  FROM players p
 WHERE p.slug = $1
`

type GetSimulationPlayerRow struct {
	ID         int64
	Slug       string
	FullName   string
	Tour       string
	Country    *string
	BestTier   string
	LastSeason int16
}

// Just enough of a player to simulate them: who they are, the level they
// compete at, and when they last played -- which together choose the serve
// baseline cell the inversion anchors on.
func (q *Queries) GetSimulationPlayer(ctx context.Context, slug string) (GetSimulationPlayerRow, error) {
	row := q.db.QueryRow(ctx, getSimulationPlayer, slug)
	var i GetSimulationPlayerRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.FullName,
		&i.Tour,
		&i.Country,
		&i.BestTier,
		&i.LastSeason,
	)
	return i, err
}

const listDrawMatches = `-- name: ListDrawMatches :many
SELECT m.round,
       m.winner_id, wp.slug AS winner_slug, wp.full_name AS winner_name, wmp.seed AS winner_seed,
       m.loser_id,  lp.slug AS loser_slug,  lp.full_name AS loser_name,  lmp.seed AS loser_seed
  FROM matches m
  JOIN players wp ON wp.id = m.winner_id
  JOIN players lp ON lp.id = m.loser_id
  LEFT JOIN match_players wmp ON wmp.match_id = m.id AND wmp.player_id = m.winner_id
  LEFT JOIN match_players lmp ON lmp.match_id = m.id AND lmp.player_id = m.loser_id
 WHERE m.tournament_id = $1
   AND NOT m.is_qualifying
   AND NOT m.is_team_event
 ORDER BY m.match_num
`

type ListDrawMatchesRow struct {
	Round      string
	WinnerID   int64
	WinnerSlug string
	WinnerName string
	WinnerSeed *int16
	LoserID    int64
	LoserSlug  string
	LoserName  string
	LoserSeed  *int16
}

// Every main-draw match of one event, with both players, for reconstructing the
// bracket.
//
// Qualifying is a separate draw and team events are not a draw at all -- 341 ATP
// "tour" events with a stated draw size of 4 are Davis Cup ties, and every one
// of their matches carries the team flag.
func (q *Queries) ListDrawMatches(ctx context.Context, tournamentID int64) ([]ListDrawMatchesRow, error) {
	rows, err := q.db.Query(ctx, listDrawMatches, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrawMatchesRow{}
	for rows.Next() {
		var i ListDrawMatchesRow
		if err := rows.Scan(
			&i.Round,
			&i.WinnerID,
			&i.WinnerSlug,
			&i.WinnerName,
			&i.WinnerSeed,
			&i.LoserID,
			&i.LoserSlug,
			&i.LoserName,
			&i.LoserSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulatableEvents = `-- name: ListSimulatableEvents :many
SELECT t.id, t.name, t.season, t.tour::text AS tour, t.tier::text AS tier,
       coalesce(t.surface::text, 'unknown')::text AS surface,
       t.start_date, count(*)::bigint AS matches
  FROM tournaments t
  JOIN matches m ON m.tournament_id = t.id
 WHERE NOT m.is_qualifying AND NOT m.is_team_event
   AND ($1::tour IS NULL OR t.tour = $1::tour)
   AND ($2::smallint IS NULL OR t.season = $2::smallint)
 GROUP BY t.id
HAVING count(*) IN (7, 15, 31, 63, 127)
 ORDER BY t.season DESC, count(*) DESC, t.name
 LIMIT $3
`

type ListSimulatableEventsParams struct {
	Tour     *Tour
	Season   *int16
	RowLimit int32
}

type ListSimulatableEventsRow struct {
	ID        int64
	Name      string
	Season    int16
	Tour      string
	Tier      string
	Surface   string
	StartDate time.Time
	Matches   int64
}

// Events whose main draw is a complete power-of-two bracket, which is the only
// shape that reconstructs. Byes and round-robin groups leave a round with the
// wrong number of matches and are excluded here rather than failing one at a
// time in the reconstruction.
func (q *Queries) ListSimulatableEvents(ctx context.Context, arg ListSimulatableEventsParams) ([]ListSimulatableEventsRow, error) {
	rows, err := q.db.Query(ctx, listSimulatableEvents, arg.Tour, arg.Season, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSimulatableEventsRow{}
	for rows.Next() {
		var i ListSimulatableEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Season,
			&i.Tour,
			&i.Tier,
			&i.Surface,
			&i.StartDate,
			&i.Matches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleRatedMatches = `-- name: SampleRatedMatches :many
SELECT m.best_of, m.deciding_set, m.tiebreaks_winner, m.tiebreaks_loser,
       t.tier::text AS tier, m.surface::text AS surface, t.season,
       w.elo::float8 AS winner_elo, l.elo::float8 AS loser_elo
  FROM matches m
  JOIN tournaments t ON t.id = m.tournament_id
  JOIN LATERAL (
        SELECT r.elo FROM ratings r
         WHERE r.player_id = m.winner_id AND r.surface = 'overall' AND r.as_of <= m.played_on
         ORDER BY r.as_of DESC LIMIT 1
       ) w ON true
  JOIN LATERAL (
        SELECT r.elo FROM ratings r
         WHERE r.player_id = m.loser_id AND r.surface = 'overall' AND r.as_of <= m.played_on
         ORDER BY r.as_of DESC LIMIT 1
       ) l ON true
 WHERE m.deciding_set IS NOT NULL
   AND NOT m.is_team_event
   AND m.surface IS NOT NULL
   AND t.tour = $1::tour
 ORDER BY m.played_on DESC, m.id
 LIMIT $2
`

type SampleRatedMatchesParams struct {
	Tour     Tour
	RowLimit int32
}

type SampleRatedMatchesRow struct {
	BestOf          int16
	DecidingSet     *bool
	TiebreaksWinner *int16
	TiebreaksLoser  *int16
	Tier            string
	Surface         string
	Season          int16
	WinnerElo       float64
	LoserElo        float64
}

// Recent completed matches with both players' ratings as they stood at the
// time, for validating what the simulation chain predicts about them.
//
// As of the match, never after it. Rating a match with a figure that already
// knows how it went is the one mistake this whole check exists to avoid.
func (q *Queries) SampleRatedMatches(ctx context.Context, arg SampleRatedMatchesParams) ([]SampleRatedMatchesRow, error) {
	rows, err := q.db.Query(ctx, sampleRatedMatches, arg.Tour, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SampleRatedMatchesRow{}
	for rows.Next() {
		var i SampleRatedMatchesRow
		if err := rows.Scan(
			&i.BestOf,
			&i.DecidingSet,
			&i.TiebreaksWinner,
			&i.TiebreaksLoser,
			&i.Tier,
			&i.Surface,
			&i.Season,
			&i.WinnerElo,
			&i.LoserElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
